import { FC, useState } from "react";
import {
  Box,
  FormControl,
  FormControlLabel,
  FormHelperText,
  Radio,
  RadioGroup,
  Typography,
} from "@mui/material";
import { useFormContext } from "react-hook-form";
import { useOrdersByCaseFileData } from "@/hooks/useInspectionOrders";
import { Inspection } from "@/models/Inspection";
import ControlledAutoComplete from "@/components/Shared/Controlled/ControlledAutoComplete";
import ControlledTextField from "@/components/Shared/Controlled/ControlledTextField";

export type OrderCreationMethod =
  | "manual_entry"
  | "create_new"
  | "link_existing";

interface OrderCreationOptionsProps {
  inspectionData: Inspection;
  isHistorical?: boolean;
}

const OrderCreationOptions: FC<OrderCreationOptionsProps> = ({
  inspectionData,
  isHistorical,
}) => {
  const { setValue, clearErrors, formState: { errors } } = useFormContext();
  const [creationMethod, setCreationMethod] = useState<OrderCreationMethod | ""> ("");
  const { data: openOrders } = useOrdersByCaseFileData(inspectionData.case_file_id, {
    isStaleInfinate: false,
  });

  const handleCreationMethodChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const method = event.target.value as OrderCreationMethod;
    setCreationMethod(method);
    setValue("orderCreationMethod", method);
    clearErrors("orderCreationMethod");

    if (method !== "manual_entry") {
      setValue("manualOrderNumber", "");
    }
    if (method !== "link_existing") {
      setValue("existingOrderId", null);
    }
  };



  return (
    <Box sx={{ mt: 2 }}>
      <Typography variant="body2" fontWeight={500} gutterBottom sx={{ fontWeight: 600 }}>
        Select how do you want to add this Order
      </Typography>

      <FormControl component="fieldset" error={!!errors.orderCreationMethod} sx={{ width: '100%', mb: 0 }}>
        <RadioGroup
          value={creationMethod}
          onChange={handleCreationMethodChange}
          sx={{
            gap: 0.5,
            '& .MuiFormControlLabel-root': {
              alignItems: 'flex-start',
              marginLeft: 0,
              marginRight: 0,
              marginBottom: 1
            },
            '& .MuiRadio-root': {
              padding: '4px 8px',
              alignSelf: 'flex-start'
            }
          }}
        >
          {isHistorical && (
            <FormControlLabel
              value="manual_entry"
              control={<Radio />}
              label={
                <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.5 }}>
                  <Typography variant="body2" fontWeight={500} sx={{ lineHeight: 1.2, mt: '0.4rem' }}>
                    Enter Historical Order #
                  </Typography>
                  <FormHelperText sx={{
                    fontSize: '12px',
                    fontStyle: 'normal',
                    fontWeight: 400,
                    lineHeight: '18px',
                    mt: 0,
                    ml: 0
                  }}>
                    Select this if the Order was already issued outside the system and must be entered retroactively.
                  </FormHelperText>
                </Box>
              }
              sx={{ alignItems: 'flex-start' }}
            />
          )}
          {/* Manual Order Number Entry */}
          {creationMethod === "manual_entry" && (
            <Box sx={{ mt: 0, ml: 2 }}>
              <ControlledTextField
                name="manualOrderNumber"
                fullWidth
                label="Manual Order #"
                placeholder="Enter existing Order number"
                isRequired
              />
            </Box>
          )}

            <FormControlLabel
                value="create_new"
                control={<Radio />}
            label={
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.5 }}>
                <Typography variant="body2" fontWeight={500} sx={{ lineHeight: 1.2, mt: '0.4rem' }}>
                  Create New Order #
                </Typography>
                <FormHelperText sx={{
                  fontSize: '12px',
                  fontStyle: 'normal',
                  fontWeight: 400,
                  lineHeight: '18px',
                  mt: 0,
                  ml: 0
                }}>
                  A new Order number will be automatically generated by the system
                </FormHelperText>
              </Box>
            }
            sx={{
              mb: 2,
              alignItems: 'flex-start'
            }}
          />

          <FormControlLabel
            value="link_existing"
            control={<Radio />}
            label={
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.5 }}>
                <Typography variant="body2" fontWeight={500} sx={{ lineHeight: 1.2, mt: '0.4rem' }}>
                  Link to Existing Order #
                </Typography>
                <FormHelperText sx={{
                  fontSize: '12px',
                  fontStyle: 'normal',
                  fontWeight: 400,
                  lineHeight: '18px',
                  mt: 0,
                  ml: 0
                }}>
                  Select this if the Order already exists in the system and applies across multiple inspections. Any updates will apply everywhere.
                </FormHelperText>
              </Box>
            }
            sx={{
              mb: 2,
              alignItems: 'flex-start'
            }}
          />
        </RadioGroup>

        {/* Existing Order Selection */}
        {creationMethod === "link_existing" && (
          <Box sx={{ mt: 0.25, ml: 2 }}>
          <ControlledAutoComplete
            name="existingOrderId"
            label="Select Existing Order #"
            options={openOrders ?? []}
            getOptionLabel={(option) => {
              if (typeof option === 'number') {
                const foundOption = openOrders.find(o => o.id === option);
                return foundOption?.order_number || '';
              }
              return option.order_number;
            }}
            isOptionEqualToValue={(option, value) => {
              if (typeof value === 'number') {
                return option.id === value;
              }
              if (value && typeof value === 'object' && 'id' in value) {
                return option.id === (value as { id: number }).id;
              }
              return false;
            }}
            placeholder="Select an option..."
            isRequired={true}
            noOptionsText="No open Orders found for this project"
            onChange={(_event, newValue) => {
              // Store only the ID, not the entire object
              let orderId = null;
              if (newValue) {
                if (Array.isArray(newValue)) {
                  orderId = newValue.length > 0 ? newValue[0].id : null;
                } else {
                  orderId = newValue.id;
                }
              }
              setValue("existingOrderId", orderId);
            }}
          />
          </Box>
        )}
        {errors.orderCreationMethod && (
          <FormHelperText>{errors.orderCreationMethod.message as string}</FormHelperText>
        )}
      </FormControl>


    </Box>
  );
};

export default OrderCreationOptions;
