/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as OidcCallbackRouteImport } from './routes/oidc-callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReviewBoardRouteImport } from './routes/_authenticated/review-board'
import { Route as AuthenticatedAdminTopicsRouteImport } from './routes/_authenticated/admin/topics'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminProponentsRouteImport } from './routes/_authenticated/admin/proponents'
import { Route as AuthenticatedAdminAgenciesRouteImport } from './routes/_authenticated/admin/agencies'
import { Route as AuthenticatedCeDatabaseRequirementsIndexRouteImport } from './routes/_authenticated/ce-database/requirements/index'
import { Route as AuthenticatedCeDatabaseInspectionsIndexRouteImport } from './routes/_authenticated/ce-database/inspections/index'
import { Route as AuthenticatedCeDatabaseComplaintsIndexRouteImport } from './routes/_authenticated/ce-database/complaints/index'
import { Route as AuthenticatedCeDatabaseCaseFilesIndexRouteImport } from './routes/_authenticated/ce-database/case-files/index'
import { Route as AuthenticatedCeDatabaseInspectionsInspectionNumberRouteImport } from './routes/_authenticated/ce-database/inspections/$inspectionNumber'
import { Route as AuthenticatedCeDatabaseComplaintsComplaintNumberRouteImport } from './routes/_authenticated/ce-database/complaints/$complaintNumber'
import { Route as AuthenticatedCeDatabaseCaseFilesCaseFileNumberRouteImport } from './routes/_authenticated/ce-database/case-files/$caseFileNumber'

const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const OidcCallbackRoute = OidcCallbackRouteImport.update({
  id: '/oidc-callback',
  path: '/oidc-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewBoardRoute =
  AuthenticatedReviewBoardRouteImport.update({
    id: '/review-board',
    path: '/review-board',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTopicsRoute =
  AuthenticatedAdminTopicsRouteImport.update({
    id: '/admin/topics',
    path: '/admin/topics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminProponentsRoute =
  AuthenticatedAdminProponentsRouteImport.update({
    id: '/admin/proponents',
    path: '/admin/proponents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAgenciesRoute =
  AuthenticatedAdminAgenciesRouteImport.update({
    id: '/admin/agencies',
    path: '/admin/agencies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCeDatabaseRequirementsIndexRoute =
  AuthenticatedCeDatabaseRequirementsIndexRouteImport.update({
    id: '/ce-database/requirements/',
    path: '/ce-database/requirements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCeDatabaseInspectionsIndexRoute =
  AuthenticatedCeDatabaseInspectionsIndexRouteImport.update({
    id: '/ce-database/inspections/',
    path: '/ce-database/inspections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCeDatabaseComplaintsIndexRoute =
  AuthenticatedCeDatabaseComplaintsIndexRouteImport.update({
    id: '/ce-database/complaints/',
    path: '/ce-database/complaints/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCeDatabaseCaseFilesIndexRoute =
  AuthenticatedCeDatabaseCaseFilesIndexRouteImport.update({
    id: '/ce-database/case-files/',
    path: '/ce-database/case-files/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCeDatabaseInspectionsInspectionNumberRoute =
  AuthenticatedCeDatabaseInspectionsInspectionNumberRouteImport.update({
    id: '/ce-database/inspections/$inspectionNumber',
    path: '/ce-database/inspections/$inspectionNumber',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCeDatabaseComplaintsComplaintNumberRoute =
  AuthenticatedCeDatabaseComplaintsComplaintNumberRouteImport.update({
    id: '/ce-database/complaints/$complaintNumber',
    path: '/ce-database/complaints/$complaintNumber',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCeDatabaseCaseFilesCaseFileNumberRoute =
  AuthenticatedCeDatabaseCaseFilesCaseFileNumberRouteImport.update({
    id: '/ce-database/case-files/$caseFileNumber',
    path: '/ce-database/case-files/$caseFileNumber',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oidc-callback': typeof OidcCallbackRoute
  '/session-expired': typeof SessionExpiredRoute
  '/review-board': typeof AuthenticatedReviewBoardRoute
  '/admin/agencies': typeof AuthenticatedAdminAgenciesRoute
  '/admin/proponents': typeof AuthenticatedAdminProponentsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/ce-database/case-files/$caseFileNumber': typeof AuthenticatedCeDatabaseCaseFilesCaseFileNumberRoute
  '/ce-database/complaints/$complaintNumber': typeof AuthenticatedCeDatabaseComplaintsComplaintNumberRoute
  '/ce-database/inspections/$inspectionNumber': typeof AuthenticatedCeDatabaseInspectionsInspectionNumberRoute
  '/ce-database/case-files/': typeof AuthenticatedCeDatabaseCaseFilesIndexRoute
  '/ce-database/complaints/': typeof AuthenticatedCeDatabaseComplaintsIndexRoute
  '/ce-database/inspections/': typeof AuthenticatedCeDatabaseInspectionsIndexRoute
  '/ce-database/requirements/': typeof AuthenticatedCeDatabaseRequirementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oidc-callback': typeof OidcCallbackRoute
  '/session-expired': typeof SessionExpiredRoute
  '/review-board': typeof AuthenticatedReviewBoardRoute
  '/admin/agencies': typeof AuthenticatedAdminAgenciesRoute
  '/admin/proponents': typeof AuthenticatedAdminProponentsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/ce-database/case-files/$caseFileNumber': typeof AuthenticatedCeDatabaseCaseFilesCaseFileNumberRoute
  '/ce-database/complaints/$complaintNumber': typeof AuthenticatedCeDatabaseComplaintsComplaintNumberRoute
  '/ce-database/inspections/$inspectionNumber': typeof AuthenticatedCeDatabaseInspectionsInspectionNumberRoute
  '/ce-database/case-files': typeof AuthenticatedCeDatabaseCaseFilesIndexRoute
  '/ce-database/complaints': typeof AuthenticatedCeDatabaseComplaintsIndexRoute
  '/ce-database/inspections': typeof AuthenticatedCeDatabaseInspectionsIndexRoute
  '/ce-database/requirements': typeof AuthenticatedCeDatabaseRequirementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/oidc-callback': typeof OidcCallbackRoute
  '/session-expired': typeof SessionExpiredRoute
  '/_authenticated/review-board': typeof AuthenticatedReviewBoardRoute
  '/_authenticated/admin/agencies': typeof AuthenticatedAdminAgenciesRoute
  '/_authenticated/admin/proponents': typeof AuthenticatedAdminProponentsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/_authenticated/ce-database/case-files/$caseFileNumber': typeof AuthenticatedCeDatabaseCaseFilesCaseFileNumberRoute
  '/_authenticated/ce-database/complaints/$complaintNumber': typeof AuthenticatedCeDatabaseComplaintsComplaintNumberRoute
  '/_authenticated/ce-database/inspections/$inspectionNumber': typeof AuthenticatedCeDatabaseInspectionsInspectionNumberRoute
  '/_authenticated/ce-database/case-files/': typeof AuthenticatedCeDatabaseCaseFilesIndexRoute
  '/_authenticated/ce-database/complaints/': typeof AuthenticatedCeDatabaseComplaintsIndexRoute
  '/_authenticated/ce-database/inspections/': typeof AuthenticatedCeDatabaseInspectionsIndexRoute
  '/_authenticated/ce-database/requirements/': typeof AuthenticatedCeDatabaseRequirementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oidc-callback'
    | '/session-expired'
    | '/review-board'
    | '/admin/agencies'
    | '/admin/proponents'
    | '/admin/staff'
    | '/admin/topics'
    | '/ce-database/case-files/$caseFileNumber'
    | '/ce-database/complaints/$complaintNumber'
    | '/ce-database/inspections/$inspectionNumber'
    | '/ce-database/case-files/'
    | '/ce-database/complaints/'
    | '/ce-database/inspections/'
    | '/ce-database/requirements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oidc-callback'
    | '/session-expired'
    | '/review-board'
    | '/admin/agencies'
    | '/admin/proponents'
    | '/admin/staff'
    | '/admin/topics'
    | '/ce-database/case-files/$caseFileNumber'
    | '/ce-database/complaints/$complaintNumber'
    | '/ce-database/inspections/$inspectionNumber'
    | '/ce-database/case-files'
    | '/ce-database/complaints'
    | '/ce-database/inspections'
    | '/ce-database/requirements'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/oidc-callback'
    | '/session-expired'
    | '/_authenticated/review-board'
    | '/_authenticated/admin/agencies'
    | '/_authenticated/admin/proponents'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/topics'
    | '/_authenticated/ce-database/case-files/$caseFileNumber'
    | '/_authenticated/ce-database/complaints/$complaintNumber'
    | '/_authenticated/ce-database/inspections/$inspectionNumber'
    | '/_authenticated/ce-database/case-files/'
    | '/_authenticated/ce-database/complaints/'
    | '/_authenticated/ce-database/inspections/'
    | '/_authenticated/ce-database/requirements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OidcCallbackRoute: typeof OidcCallbackRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oidc-callback': {
      id: '/oidc-callback'
      path: '/oidc-callback'
      fullPath: '/oidc-callback'
      preLoaderRoute: typeof OidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/review-board': {
      id: '/_authenticated/review-board'
      path: '/review-board'
      fullPath: '/review-board'
      preLoaderRoute: typeof AuthenticatedReviewBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/topics': {
      id: '/_authenticated/admin/topics'
      path: '/admin/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AuthenticatedAdminTopicsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/proponents': {
      id: '/_authenticated/admin/proponents'
      path: '/admin/proponents'
      fullPath: '/admin/proponents'
      preLoaderRoute: typeof AuthenticatedAdminProponentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/agencies': {
      id: '/_authenticated/admin/agencies'
      path: '/admin/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AuthenticatedAdminAgenciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ce-database/requirements/': {
      id: '/_authenticated/ce-database/requirements/'
      path: '/ce-database/requirements'
      fullPath: '/ce-database/requirements/'
      preLoaderRoute: typeof AuthenticatedCeDatabaseRequirementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ce-database/inspections/': {
      id: '/_authenticated/ce-database/inspections/'
      path: '/ce-database/inspections'
      fullPath: '/ce-database/inspections/'
      preLoaderRoute: typeof AuthenticatedCeDatabaseInspectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ce-database/complaints/': {
      id: '/_authenticated/ce-database/complaints/'
      path: '/ce-database/complaints'
      fullPath: '/ce-database/complaints/'
      preLoaderRoute: typeof AuthenticatedCeDatabaseComplaintsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ce-database/case-files/': {
      id: '/_authenticated/ce-database/case-files/'
      path: '/ce-database/case-files'
      fullPath: '/ce-database/case-files/'
      preLoaderRoute: typeof AuthenticatedCeDatabaseCaseFilesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ce-database/inspections/$inspectionNumber': {
      id: '/_authenticated/ce-database/inspections/$inspectionNumber'
      path: '/ce-database/inspections/$inspectionNumber'
      fullPath: '/ce-database/inspections/$inspectionNumber'
      preLoaderRoute: typeof AuthenticatedCeDatabaseInspectionsInspectionNumberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ce-database/complaints/$complaintNumber': {
      id: '/_authenticated/ce-database/complaints/$complaintNumber'
      path: '/ce-database/complaints/$complaintNumber'
      fullPath: '/ce-database/complaints/$complaintNumber'
      preLoaderRoute: typeof AuthenticatedCeDatabaseComplaintsComplaintNumberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ce-database/case-files/$caseFileNumber': {
      id: '/_authenticated/ce-database/case-files/$caseFileNumber'
      path: '/ce-database/case-files/$caseFileNumber'
      fullPath: '/ce-database/case-files/$caseFileNumber'
      preLoaderRoute: typeof AuthenticatedCeDatabaseCaseFilesCaseFileNumberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedReviewBoardRoute: typeof AuthenticatedReviewBoardRoute
  AuthenticatedAdminAgenciesRoute: typeof AuthenticatedAdminAgenciesRoute
  AuthenticatedAdminProponentsRoute: typeof AuthenticatedAdminProponentsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTopicsRoute: typeof AuthenticatedAdminTopicsRoute
  AuthenticatedCeDatabaseCaseFilesCaseFileNumberRoute: typeof AuthenticatedCeDatabaseCaseFilesCaseFileNumberRoute
  AuthenticatedCeDatabaseComplaintsComplaintNumberRoute: typeof AuthenticatedCeDatabaseComplaintsComplaintNumberRoute
  AuthenticatedCeDatabaseInspectionsInspectionNumberRoute: typeof AuthenticatedCeDatabaseInspectionsInspectionNumberRoute
  AuthenticatedCeDatabaseCaseFilesIndexRoute: typeof AuthenticatedCeDatabaseCaseFilesIndexRoute
  AuthenticatedCeDatabaseComplaintsIndexRoute: typeof AuthenticatedCeDatabaseComplaintsIndexRoute
  AuthenticatedCeDatabaseInspectionsIndexRoute: typeof AuthenticatedCeDatabaseInspectionsIndexRoute
  AuthenticatedCeDatabaseRequirementsIndexRoute: typeof AuthenticatedCeDatabaseRequirementsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedReviewBoardRoute: AuthenticatedReviewBoardRoute,
  AuthenticatedAdminAgenciesRoute: AuthenticatedAdminAgenciesRoute,
  AuthenticatedAdminProponentsRoute: AuthenticatedAdminProponentsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminTopicsRoute: AuthenticatedAdminTopicsRoute,
  AuthenticatedCeDatabaseCaseFilesCaseFileNumberRoute:
    AuthenticatedCeDatabaseCaseFilesCaseFileNumberRoute,
  AuthenticatedCeDatabaseComplaintsComplaintNumberRoute:
    AuthenticatedCeDatabaseComplaintsComplaintNumberRoute,
  AuthenticatedCeDatabaseInspectionsInspectionNumberRoute:
    AuthenticatedCeDatabaseInspectionsInspectionNumberRoute,
  AuthenticatedCeDatabaseCaseFilesIndexRoute:
    AuthenticatedCeDatabaseCaseFilesIndexRoute,
  AuthenticatedCeDatabaseComplaintsIndexRoute:
    AuthenticatedCeDatabaseComplaintsIndexRoute,
  AuthenticatedCeDatabaseInspectionsIndexRoute:
    AuthenticatedCeDatabaseInspectionsIndexRoute,
  AuthenticatedCeDatabaseRequirementsIndexRoute:
    AuthenticatedCeDatabaseRequirementsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OidcCallbackRoute: OidcCallbackRoute,
  SessionExpiredRoute: SessionExpiredRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
