replicaCount: 2
cors_origin: https://compliance.eao.gov.bc.ca,

image:
  repository: image-registry.openshift-image-registry.svc:5000/c8b80a-tools/compliance-api
  pullPolicy: Always
  namespace: c8b80a-tools
  # Overrides the image tag whose default is the chart appVersion.
  tag: "prod"

resources:
  cpu:
    limit: 200m
    request: 150m
  memory:
    limit: 300Mi
    request: 256Mi

database:
  secret: compliance-patroni
  service:
    name: compliance-patroni
    port: 5432

auth_service:
  url: https://auth-api-c72cba-prod.apps.gold.devops.gov.bc.ca
track_service:
  url: https://epictrack-api-c72cba-prod.apps.gold.devops.gov.bc.ca
storage_service:
  url: https://nrs.objectstore.gov.bc.ca
  s3_bucket: test-epic
doc_service:
  url: https://epic-document-api-c8b80a-prod.apps.gold.devops.gov.bc.ca
docgen_service:
  url: https://docgen-api-c72cba-prod.apps.gold.devops.gov.bc.ca

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

auth:
  jwt:
    alg: RS256
    aud: epic-compliance
    cacheEnabled: true
    issuer: https://loginproxy.gov.bc.ca/auth/realms/eao-epic
    cacheTimeout: "300"
    wellKnownConfig: https://loginproxy.gov.bc.ca/auth/realms/eao-epic/.well-known/openid-configuration
  keycloak:
    uri: https://loginproxy.gov.bc.ca
    realm: eao-epic
    adminClientId:
    adminClientSecret:
python:
  pythonBuffered: 1
  connectTimeout: 60
vault:
  secretName: compliance.env
  path: c8b80a-prod/compliance.env
  authPath: auth/k8s-gold
  namespace: platform-services
  role: c8b80a-prod

serviceAccount:
  name: c8b80a-vault