replicaCount: 1
flaskEnv: development
cors_origin: https://compliance-web-c8b80a-dev.apps.gold.devops.gov.bc.ca,http://localhost:5173,https://dev.compliance.eao.gov.bc.ca

image:
  repository: image-registry.openshift-image-registry.svc:5000/c8b80a-tools/compliance-api
  pullPolicy: Always
  namespace: c8b80a-tools
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

resources:
  cpu:
    limit: 250m
    request: 150m
  memory:
    limit: 300Mi
    request: 256Mi

database:
  secret: compliance-patroni
  service:
    name: compliance-patroni
    port: 5432

auth_service:
  url: https://auth-api-c72cba-dev.apps.gold.devops.gov.bc.ca
track_service:
  url: https://epictrack-api-c72cba-dev.apps.gold.devops.gov.bc.ca
storage_service:
  url: https://nrs.objectstore.gov.bc.ca
  s3_bucket: dev-epic
doc_service:
  url: https://epic-document-api-c8b80a-dev.apps.gold.devops.gov.bc.ca
docgen_service:
  url: https://docgen-api-c72cba-dev.apps.gold.devops.gov.bc.ca

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

auth:
  jwt:
    alg: RS256
    aud: epic-compliance
    cacheEnabled: true
    issuer: https://dev.loginproxy.gov.bc.ca/auth/realms/eao-epic
    cacheTimeout: "300"
    wellKnownConfig: https://dev.loginproxy.gov.bc.ca/auth/realms/eao-epic/.well-known/openid-configuration
  keycloak:
    uri: https://dev.loginproxy.gov.bc.ca
    realm: eao-epic
    adminClientId:
    adminClientSecret:
python:
  pythonBuffered: 1
  connectTimeout: 60
cdogs:  
  tokenEndpoint: https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token
  apiEndpoint: https://cdogs-dev.api.gov.bc.ca/api/v2
  clientId:
  clientSecret:

vault:
  secretName: compliance.test.env
  path: c8b80a-nonprod/compliance.test.env
  authPath: auth/k8s-gold
  namespace: platform-services
  role: c8b80a-nonprod

serviceAccount:
  name: c8b80a-vault

gunicorn:
  workerCount: 1
  threadCount: 2
  connectionCount: 250
  timeout: 60
