apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
data:
  JWT_OIDC_ALGORITHMS: {{ .Values.auth.jwt.alg }}
  JWT_OIDC_AUDIENCE: {{ .Values.auth.jwt.aud }}
  JWT_OIDC_CACHING_ENABLED: "{{ .Values.auth.jwt.cacheEnabled }}"
  JWT_OIDC_ISSUER: {{ .Values.auth.jwt.issuer }}
  JWT_OIDC_JWKS_CACHE_TIMEOUT: "{{ .Values.auth.jwt.cacheTimeout }}"
  JWT_OIDC_WELL_KNOWN_CONFIG: {{ .Values.auth.jwt.wellKnownConfig }}
  PYTHONBUFFERED: "{{ .Values.python.pythonBuffered }}"
  KEYCLOAK_BASE_URL: {{ .Values.auth.keycloak.uri }}
  KEYCLOAK_REALM_NAME: {{ .Values.auth.keycloak.realm }}
  CONNECT_TIMEOUT: "{{ .Values.python.connectTimeout }}"
  DOC_SERVICE_URL: {{ .Values.doc_service.url }}
  EPIC_TRACK_URL: {{ .Values.track_service.url }}
  AUTH_BASE_URL: {{ .Values.auth_service.url }}
  STORAGE_HOST_URL: {{ .Values.storage_service.url }}
  S3_BUCKET: {{ .Values.storage_service.s3_bucket }}
  DOCGEN_SERVICE_URL: {{ .Values.docgen_service.url }}
  GUNICORN_WORKERS: "{{ .Values.gunicorn.workerCount }}"
  GUNICORN_WORKER_THREADS: "{{ .Values.gunicorn.threadCount }}"
  GUNICORN_WORKER_CONNECTIONS: "{{ .Values.gunicorn.connectionCount }}"
  GUNICORN_TIMEOUT: "{{ .Values.gunicorn.timeout }}"