import type { Meta, StoryObj } from "@storybook/react";
import PageLink from "@/components/Shared/PageLink";
import { RouterDecorator } from "../../decorators/RouterDecorator";

const meta: Meta<typeof PageLink> = {
  title: "Shared/PageLink",
  component: PageLink,
  parameters: {
    layout: "padded",
  },
  decorators: [RouterDecorator],
  tags: ["autodocs"],
  argTypes: {
    to: {
      control: "text",
      description: "Route path",
    },
    params: {
      control: "object",
      description: "Route parameters",
    },
    linkText: {
      control: "text",
      description: "Text to display for the link",
    },
    underline: {
      control: "select",
      options: ["none", "hover", "always"],
      description: "Underline style",
    },
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    to: "/ce-database/case-files",
    linkText: "View Case Files",
  },
};

export const WithParams: Story = {
  args: {
    to: "/ce-database/case-files/$caseFileId",
    params: { caseFileId: "CF-2024-001" },
    linkText: "Case File CF-2024-001",
  },
};

export const NoUnderline: Story = {
  args: {
    to: "/admin/users",
    linkText: "User Management",
    underline: "none",
  },
};

export const AlwaysUnderlined: Story = {
  args: {
    to: "/reports",
    linkText: "Generate Report",
    underline: "always",
  },
};

export const WithMultipleParams: Story = {
  args: {
    to: "/admin/users/$userId/edit/$section",
    params: { userId: "123", section: "profile" },
    linkText: "Edit User Profile",
  },
};

export const AutoGeneratedText: Story = {
  args: {
    to: "/case-files/$caseFileNumber",
    params: { caseFileNumber: "CF-2024-002" },
  },
};
