"""remove exemption_order_number field

Revision ID: 026779d28e0c
Revises: 5291fcced72e
Create Date: 2025-07-24 15:18:33.731676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026779d28e0c'
down_revision = '5291fcced72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_req_source_details', schema=None) as batch_op:
        batch_op.drop_column('exemption_order_number')

    with op.batch_alter_table('inspection_req_source_details_version', schema=None) as batch_op:
        batch_op.drop_column('exemption_order_number_mod')
        batch_op.drop_column('exemption_order_number')
    op.execute("UPDATE requirement_sources SET source_title = 'Exemption Order # ${eac#}' WHERE id = 12")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_req_source_details_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exemption_order_number', sa.VARCHAR(), autoincrement=False, nullable=True, comment='The optional exemption order number associated with requirement sources as Exemption Order'))
        batch_op.add_column(sa.Column('exemption_order_number_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))

    with op.batch_alter_table('inspection_req_source_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exemption_order_number', sa.VARCHAR(), autoincrement=False, nullable=True, comment='The optional exemption order number associated with requirement sources as Exemption Order'))
    op.execute("UPDATE requirement_sources SET source_title = '' WHERE id = 12")
    # ### end Alembic commands ###
