"""orders backend tables

Revision ID: 0788ce22cad3
Revises: ef5bf004ac09
Create Date: 2025-04-30 10:08:13.601415

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = '0788ce22cad3'
down_revision = 'ef5bf004ac09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_inspection_requirement_maps_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('order_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('inspection_requirement_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('order_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inspection_requirement_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('order_inspection_requirement_maps_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_inspection_requirement_maps_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_inspection_requirement_maps_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_inspection_requirement_maps_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('orders_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('where_as', sa.String(), autoincrement=False, nullable=True),
    sa.Column('now_therefore', sa.String(), autoincrement=False, nullable=True),
    sa.Column('order_number', sa.String(), autoincrement=False, nullable=True),
    sa.Column('section_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('date_issued', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('intended_issuance_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('inspection_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('issuing_officer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('order_status', sa.Enum('OPEN', 'CLOSED', 'RESCINDED', name='orderstatusenum'), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('where_as_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('now_therefore_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('order_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('section_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_issued_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('intended_issuance_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inspection_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('issuing_officer_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('order_status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('orders_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_version_transaction_id'), ['transaction_id'], unique=False)

    sections_table = op.create_table('sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier of the section'),
    sa.Column('name', sa.String(), nullable=False, comment='The name of the section'),
    sa.Column('act', sa.Integer(), nullable=False, comment='The act associated with the section'),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index('ix_sections_unique_name_act_active', ['name', 'act'], unique=True, postgresql_where=False)

    op.create_table('sections_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier of the section'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True, comment='The name of the section'),
    sa.Column('act', sa.Integer(), autoincrement=False, nullable=True, comment='The act associated with the section'),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('act_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('sections_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('where_as', sa.String(), nullable=True),
    sa.Column('now_therefore', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('date_issued', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intended_issuance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('issuing_officer_id', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.Enum('OPEN', 'CLOSED', 'RESCINDED', name='orderstatusenum'), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['issuing_officer_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_inspection_requirement_maps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('inspection_requirement_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['inspection_requirement_id'], ['inspection_requirements.id'], name='order_inspection_map_requirement_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_inspection_map_order_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # Insert sections data

    current_time = datetime.datetime.now(datetime.timezone.utc)
    
    op.bulk_insert(
        sections_table,
        [
            {
                'name': '53',
                'act': 2018,
                'is_active': True,
                'is_deleted': False,
                'created_by': 'SYSTEM',
                'created_date': current_time
            },
            {
                'name': '34',
                'act': 2002,
                'is_active': True,
                'is_deleted': False,
                'created_by': 'SYSTEM',
                'created_date': current_time
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_inspection_requirement_maps')
    op.drop_table('orders')
    with op.batch_alter_table('sections_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_sections_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_sections_version_end_transaction_id'))

    op.drop_table('sections_version')
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index('ix_sections_unique_name_act_active', postgresql_where=False)

    op.drop_table('sections')
    with op.batch_alter_table('orders_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_orders_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_orders_version_end_transaction_id'))

    op.drop_table('orders_version')
    with op.batch_alter_table('order_inspection_requirement_maps_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_inspection_requirement_maps_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_order_inspection_requirement_maps_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_order_inspection_requirement_maps_version_end_transaction_id'))

    op.drop_table('order_inspection_requirement_maps_version')
    # ### end Alembic commands ###
