"""enforcement_action change+restorative justice option

Revision ID: 0f766f32027e
Revises: ec9d056ba2f9
Create Date: 2025-08-20 10:23:15.983007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f766f32027e'
down_revision = 'ec9d056ba2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enforcement_action_options', schema=None) as batch_op:
        batch_op.drop_column('is_historical')

    with op.batch_alter_table('enforcement_action_options_version', schema=None) as batch_op:
        batch_op.drop_column('is_historical')
        batch_op.drop_column('is_historical_mod')

    op.execute("""
        INSERT INTO enforcement_action_options (id, name, sort_order, created_by, updated_by, created_date, updated_date, is_active, is_deleted)
        VALUES (12, 'Restorative Justice', 12, 'system', 'system', NOW(), NOW(), true, false);
    """)
    # Update the sequence to continue from 13
    op.execute("SELECT setval('enforcement_action_options_id_seq', 12, true);")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('enforcement_action_options_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_historical_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_historical', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))

    with op.batch_alter_table('enforcement_action_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_historical', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # Delete "Restorative Justice" option from enforcement_action_options table
    op.execute("DELETE FROM enforcement_action_options WHERE name = 'Restorative Justice';")
    
    # Reset the sequence to start from 11
    op.execute("SELECT setval('enforcement_action_options_id_seq', 11, true);")

    # ### end Alembic commands ###
