"""approval status changes+ approved_date in inspection

Revision ID: 1637128b4b97
Revises: d17621c35d33
Create Date: 2025-06-17 13:23:40.034314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1637128b4b97'
down_revision = 'd17621c35d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_record_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('inspection_record_approvals_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approved_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    table_enum_type_map = {
        "inspection_record_approvals": "irapprovalstatusenum",
        "order_approvals": "orderapprovalstatusenum",
        "warning_letter_approvals": "warningletterapprovalstatusenum",
    }
    for table, enum_type in table_enum_type_map.items():
        op.execute(f"truncate {table} RESTART IDENTITY")
        op.execute(f"truncate {table}_version RESTART IDENTITY")
        op.execute(f"CREATE TYPE {enum_type}_old AS ENUM ('APPROVAL_PENDING', 'APPROVED', 'NOT_APPROVED')")
        op.execute(f"ALTER TABLE {table} ALTER COLUMN approval_status TYPE {enum_type}_old USING approval_status::text::{enum_type}_old;")
        op.execute(f"ALTER TABLE {table}_version ALTER COLUMN approval_status TYPE {enum_type}_old USING approval_status::text::{enum_type}_old;")
        op.execute(f"DROP TYPE {enum_type};")
        op.execute(f"ALTER TYPE {enum_type}_old RENAME TO {enum_type};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_record_approvals_version', schema=None) as batch_op:
        batch_op.drop_column('approved_date_mod')
        batch_op.drop_column('approved_date')

    with op.batch_alter_table('inspection_record_approvals', schema=None) as batch_op:
        batch_op.drop_column('approved_date')
    table_enum_type_map = {
        "inspection_record_approvals": "irapprovalstatusenum",
        "order_approvals": "orderapprovalstatusenum",
        "warning_letter_approvals": "warningletterapprovalstatusenum",
    }
    for table, enum_type in table_enum_type_map.items():
        op.execute(f"CREATE TYPE {enum_type}_old AS ENUM ('DECISION_PENDING', 'APPROVED', 'NOT_APPROVED')")
        op.execute(f"ALTER TABLE {table} ALTER COLUMN approval_status TYPE {enum_type}_old USING approval_status::text::{enum_type}_old;")
        op.execute(f"ALTER TABLE {table}_version ALTER COLUMN approval_status TYPE {enum_type}_old USING approval_status::text::{enum_type}_old;")
        op.execute(f"DROP TYPE {enum_type};")
        op.execute(f"ALTER TYPE {enum_type}_old RENAME TO {enum_type};")
    # ### end Alembic commands ###
