"""inspection_images table creation

Revision ID: 199147664d8e
Revises: ff7d002a8a12
Create Date: 2025-02-18 10:11:33.606897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199147664d8e'
down_revision = 'ff7d002a8a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_req_images_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('requirement_id', sa.Integer(), autoincrement=False, nullable=True, comment='The requirement id'),
    sa.Column('sort_order', sa.Integer(), autoincrement=False, nullable=True, comment='The order of images. grouped by the type.'),
    sa.Column('image_type', sa.Enum('PHOTO', 'FIGURE', name='imagetype'), autoincrement=False, nullable=True),
    sa.Column('original_file_name', sa.String(), autoincrement=False, nullable=True, comment='The original filename of the uploaded image'),
    sa.Column('date_taken', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='The time of the image when it is captured'),
    sa.Column('taken_by_id', sa.Integer(), autoincrement=False, nullable=True, comment='The unique identifier of the staff who captured the image'),
    sa.Column('caption', sa.String(), autoincrement=False, nullable=True, comment='The caption of the image'),
    sa.Column('url', sa.String(), autoincrement=False, nullable=True, comment='The actual url of the final uploaded image'),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('requirement_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('image_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('original_file_name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_taken_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('taken_by_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('caption_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('url_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('inspection_req_images_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_req_images_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_req_images_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_req_images_version_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_req_images_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('inspection_req_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('requirement_id', sa.Integer(), nullable=False, comment='The requirement id'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='The order of images. grouped by the type.'),
    sa.Column('image_type', sa.Enum('PHOTO', 'FIGURE', name='imagetype'), nullable=False),
    sa.Column('original_file_name', sa.String(), nullable=False, comment='The original filename of the uploaded image'),
    sa.Column('date_taken', sa.DateTime(timezone=True), nullable=False, comment='The time of the image when it is captured'),
    sa.Column('taken_by_id', sa.Integer(), nullable=False, comment='The unique identifier of the staff who captured the image'),
    sa.Column('caption', sa.String(), nullable=True, comment='The caption of the image'),
    sa.Column('url', sa.String(), nullable=False, comment='The actual url of the final uploaded image'),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['inspection_requirements.id'], name='inspection_req_images_req_id_fkey'),
    sa.ForeignKeyConstraint(['taken_by_id'], ['staff_users.id'], name='inspection_images_taken_by_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_req_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_req_images_requirement_id'), ['requirement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_req_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_req_images_requirement_id'))

    op.drop_table('inspection_req_images')
    with op.batch_alter_table('inspection_req_images_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_req_images_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_req_images_version_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_req_images_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_req_images_version_end_transaction_id'))

    op.drop_table('inspection_req_images_version')
    # ### end Alembic commands ###
