"""enforcement requirement map

Revision ID: 20afe60273fb
Revises: 6c3b6755e2dc
Create Date: 2025-01-10 11:12:08.390578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20afe60273fb'
down_revision = '6c3b6755e2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_req_enforcement_mappings_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('requirement_id', sa.Integer(), autoincrement=False, nullable=True, comment='The requirement id'),
    sa.Column('enforcement_action_id', sa.Integer(), autoincrement=False, nullable=True, comment='The enforcement action taken on the requirement'),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('requirement_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('enforcement_action_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('inspection_req_enforcement_mappings_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_req_enforcement_mappings_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_req_enforcement_mappings_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_req_enforcement_mappings_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('inspection_req_enforcement_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('requirement_id', sa.Integer(), nullable=False, comment='The requirement id'),
    sa.Column('enforcement_action_id', sa.Integer(), nullable=True, comment='The enforcement action taken on the requirement'),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['enforcement_action_id'], ['enforcement_action_options.id'], name='insepction_req_enf_map_fkey'),
    sa.ForeignKeyConstraint(['requirement_id'], ['inspection_requirements.id'], name='inspection_req_enf_map_req_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_requirements', schema=None) as batch_op:
        batch_op.create_index('unique_non_deleted_sort_order', ['inspection_id', 'sort_order'], unique=True, postgresql_where=sa.text('is_deleted IS false'))
        batch_op.drop_constraint('insepction_requirements_enforcement_action_fkey', type_='foreignkey')
        batch_op.drop_column('enforcement_action_id')

    with op.batch_alter_table('inspection_requirements_version', schema=None) as batch_op:
        batch_op.drop_column('enforcement_action_id')
        batch_op.drop_column('enforcement_action_id_mod')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_requirements_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enforcement_action_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('enforcement_action_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='The enforcement action taken on the requirement'))

    with op.batch_alter_table('inspection_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enforcement_action_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='The enforcement action taken on the requirement'))
        batch_op.create_foreign_key('insepction_requirements_enforcement_action_fkey', 'enforcement_action_options', ['enforcement_action_id'], ['id'])
        batch_op.drop_index('unique_non_deleted_sort_order', postgresql_where=sa.text('is_deleted IS false'))

    op.drop_table('inspection_req_enforcement_mappings')
    with op.batch_alter_table('inspection_req_enforcement_mappings_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_req_enforcement_mappings_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_req_enforcement_mappings_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_req_enforcement_mappings_version_end_transaction_id'))

    op.drop_table('inspection_req_enforcement_mappings_version')
    # ### end Alembic commands ###
