"""project_status change in inspection

Revision ID: 20e336b523d9
Revises: cde897a20139
Create Date: 2024-11-18 11:37:57.451442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20e336b523d9'
down_revision = 'cde897a20139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_status_options_version', schema=None) as batch_op:
        batch_op.drop_index('ix_project_status_options_version_end_transaction_id')
        batch_op.drop_index('ix_project_status_options_version_operation_type')
        batch_op.drop_index('ix_project_status_options_version_transaction_id')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_constraint('inspection_project_status_id_project_status_options_id_fkey', type_='foreignkey')
    status_map = {
        "1": "13",
        "2": "14",
        "3": "15",
        "4": "17",
        "5": "13",
        "6": "13"
    }
    for status in status_map.keys():
        op.execute(f"UPDATE inspections set project_status_id = {status_map[status]} WHERE project_status_id = {status}")
    op.drop_table('project_status_options_version')
    op.drop_table('project_status_options')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_foreign_key('inspection_project_status_id_project_status_options_id_fkey', 'project_status_options', ['project_status_id'], ['id'])

    op.create_table('project_status_options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='The unique identifier of the project status option'),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='The name of the option'),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True, comment='Order of priority. Mainly used order the options while listing'),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='project_status_options_pkey'),
    sa.UniqueConstraint('name', name='project_status_options_name_key')
    )
    op.create_table('project_status_options_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False, comment='The unique identifier of the project status option'),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='The name of the option'),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True, comment='Order of priority. Mainly used order the options while listing'),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('sort_order_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_date_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_date_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_by_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_by_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_active_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_deleted_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name='project_status_options_version_pkey')
    )
    with op.batch_alter_table('project_status_options_version', schema=None) as batch_op:
        batch_op.create_index('ix_project_status_options_version_transaction_id', ['transaction_id'], unique=False)
        batch_op.create_index('ix_project_status_options_version_operation_type', ['operation_type'], unique=False)
        batch_op.create_index('ix_project_status_options_version_end_transaction_id', ['end_transaction_id'], unique=False)

    # ### end Alembic commands ###
