"""requirement_source_name_change

Revision ID: 21278058610c
Revises: e8129db0036b
Create Date: 2024-10-07 16:13:06.721179

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21278058610c'
down_revision = 'e8129db0036b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("UPDATE requirement_sources set name='Schedule B - Table of Conditions' WHERE name='Schedule B'"))
    op.execute(sa.text("UPDATE requirement_sources set name='Schedule A - Certified Project Description' WHERE name='Certified Project Description'"))
    op.execute(sa.text("UPDATE requirement_sources SET sort_order=9 WHERE sort_order=8"))
    op.execute(sa.text(f"INSERT INTO requirement_sources(name, sort_order, created_by, created_date) VALUES ('Other', 8,'system', '{datetime.utcnow()}')"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("UPDATE requirement_sources set name='Schedule B' WHERE name='Schedule B - Table of Conditions'"))
    op.execute(sa.text("UPDATE requirement_sources set name='Certified Project Description' WHERE name='Schedule A - Certified Project Description'"))
    op.execute(sa.text("DELETE from requirement_sources WHERE name='Other'"))
    op.execute(sa.text("UPDATE requirement_sources SET sort_order=8 WHERE sort_order=9"))
    # ### end Alembic commands ###
