"""lead to primary change

Revision ID: 31ce9015c9b0
Revises: 6d8d7b605eba
Create Date: 2024-10-23 13:32:29.676876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31ce9015c9b0'
down_revision = '6d8d7b605eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE inspections CASCADE")
    with op.batch_alter_table('agencies_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agencies_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agencies_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agencies_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('case_file_initiation_options_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_file_initiation_options_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_file_initiation_options_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_file_initiation_options_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('case_file_officers_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_file_officers_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_file_officers_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_file_officers_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_officer_id', sa.Integer(), nullable=True, comment='The primary officer who created the case file'))
        batch_op.drop_constraint('case_files_created_staff_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('case_files_primary_staff_id_fkey', 'staff_users', ['primary_officer_id'], ['id'])
        batch_op.drop_column('lead_officer_id')

    with op.batch_alter_table('case_files_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_officer_id', sa.Integer(), autoincrement=False, nullable=True, comment='The primary officer who created the case file'))
        batch_op.add_column(sa.Column('primary_officer_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.create_index(batch_op.f('ix_case_files_version_case_file_number'), ['case_file_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_files_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_files_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_files_version_transaction_id'), ['transaction_id'], unique=False)
        batch_op.drop_column('lead_officer_id')
        batch_op.drop_column('lead_officer_id_mod')

    with op.batch_alter_table('complaint_req_eac_details_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_req_eac_details_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_req_eac_details_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_req_eac_details_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('complaint_req_order_details_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_req_order_details_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_req_order_details_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_req_order_details_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('complaint_req_schedule_b_details_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_req_schedule_b_details_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_req_schedule_b_details_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_req_schedule_b_details_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('complaint_requirement_details_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_requirement_details_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_requirement_details_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_requirement_details_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('complaint_source_contacts_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_source_contacts_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_source_contacts_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_source_contacts_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('complaint_sources_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_sources_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_sources_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_sources_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('complaint_unapproved_projects_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_unapproved_projects_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_unapproved_projects_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_unapproved_projects_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_officer_id', sa.Integer(), nullable=True, comment='The primary officer who created the inspection'))
        batch_op.drop_constraint('inspection_lead_officer_id_staff_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('inspection_primary_officer_id_staff_id_fkey', 'staff_users', ['primary_officer_id'], ['id'])
        batch_op.drop_column('lead_officer_id')
        batch_op.drop_column('source_first_nation_id')

    with op.batch_alter_table('complaints_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_officer_id', sa.Integer(), autoincrement=False, nullable=True, comment='The primary officer who created the inspection'))
        batch_op.add_column(sa.Column('primary_officer_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.create_index(batch_op.f('ix_complaints_version_complaint_number'), ['complaint_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_version_transaction_id'), ['transaction_id'], unique=False)
        batch_op.drop_column('lead_officer_id')
        batch_op.drop_column('lead_officer_id_mod')
        batch_op.drop_column('source_first_nation_id_mod')
        batch_op.drop_column('source_first_nation_id')
    contextenum = sa.Enum('INSPECTION', 'COMPLAINT', 'CASE_FILE', 'ORDER', name='contextenum')
    contextenum.create(op.get_bind())
    with op.batch_alter_table('continuation_report_keys', schema=None) as batch_op:
        batch_op.execute('''
        ALTER TABLE continuation_report_keys
        ALTER COLUMN key_context
        TYPE contextenum USING key_context::text::contextenum;
    ''')
        batch_op.create_index(batch_op.f('ix_continuation_report_keys_report_id'), ['report_id'], unique=False)

    with op.batch_alter_table('continuation_report_keys_version', schema=None) as batch_op:
        batch_op.execute('''
        ALTER TABLE continuation_report_keys_version
        ALTER COLUMN key_context
        TYPE contextenum USING key_context::text::contextenum;
    ''')
        batch_op.create_index(batch_op.f('ix_continuation_report_keys_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_continuation_report_keys_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_continuation_report_keys_version_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_continuation_report_keys_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('continuation_reports', schema=None) as batch_op:
        batch_op.execute('''
        ALTER TABLE continuation_reports
        ALTER COLUMN context_type
        TYPE contextenum USING context_type::text::contextenum;
    ''')
        batch_op.create_index(batch_op.f('ix_continuation_reports_case_file_id'), ['case_file_id'], unique=False)

    with op.batch_alter_table('continuation_reports_version', schema=None) as batch_op:
        batch_op.execute('''
        ALTER TABLE continuation_reports_version
        ALTER COLUMN context_type
        TYPE contextenum USING context_type::text::contextenum;
    ''')
        batch_op.create_index(batch_op.f('ix_continuation_reports_version_case_file_id'), ['case_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_continuation_reports_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_continuation_reports_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_continuation_reports_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inspection_agencies_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_agencies_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_agencies_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_agencies_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inspection_attendance_mappings_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_attendance_mappings_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_attendance_mappings_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_attendance_mappings_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inspection_attendance_options_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_attendance_options_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_attendance_options_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_attendance_options_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inspection_firstnations_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_firstnations_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_firstnations_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_firstnations_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inspection_initiation_options_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_initiation_options_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_initiation_options_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_initiation_options_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inspection_officers_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_officers_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_officers_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_officers_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inspection_other_attendances_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_other_attendances_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_other_attendances_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_other_attendances_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inspection_type_options_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_type_options_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_type_options_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_type_options_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inspection_types_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_types_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_types_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_types_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inspection_unapproved_projects_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_unapproved_projects_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_unapproved_projects_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_unapproved_projects_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_officer_id', sa.Integer(), nullable=False, comment='The primary officer who created the inspection'))
        batch_op.drop_constraint('inspection_lead_officer_id_staff_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('inspection_primary_officer_id_staff_id_fkey', 'staff_users', ['primary_officer_id'], ['id'])
        batch_op.drop_column('lead_officer_id')

    with op.batch_alter_table('inspections_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_officer_id', sa.Integer(), autoincrement=False, nullable=True, comment='The primary officer who created the inspection'))
        batch_op.add_column(sa.Column('primary_officer_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.create_index(batch_op.f('ix_inspections_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_version_ir_number'), ['ir_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_version_transaction_id'), ['transaction_id'], unique=False)
        batch_op.drop_column('lead_officer_id')
        batch_op.drop_column('lead_officer_id_mod')

    with op.batch_alter_table('ir_status_options_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ir_status_options_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ir_status_options_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ir_status_options_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('positions_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('project_status_options_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_status_options_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_options_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_options_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('projects_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('requirement_sources_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_sources_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_sources_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_sources_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('staff_users_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_users_version_auth_user_guid'), ['auth_user_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_users_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_users_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_users_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('topics_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_version_transaction_id'), ['transaction_id'], unique=False)
    op.execute(f"DROP TYPE IF EXISTS contexttypeenum")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    contexttypeenum = sa.Enum('INSPECTION', 'COMPLAINT', 'CASE_FILE', 'ORDER', name='contexttypeenum')
    contexttypeenum.create(op.get_bind())
    with op.batch_alter_table('topics_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_topics_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_topics_version_end_transaction_id'))

    with op.batch_alter_table('staff_users_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_users_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_staff_users_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_staff_users_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_staff_users_version_auth_user_guid'))

    with op.batch_alter_table('requirement_sources_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_sources_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_sources_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_requirement_sources_version_end_transaction_id'))

    with op.batch_alter_table('projects_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_projects_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_projects_version_end_transaction_id'))

    with op.batch_alter_table('project_status_options_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_status_options_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_project_status_options_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_project_status_options_version_end_transaction_id'))

    with op.batch_alter_table('positions_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_positions_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_positions_version_end_transaction_id'))

    with op.batch_alter_table('ir_status_options_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ir_status_options_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ir_status_options_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_ir_status_options_version_end_transaction_id'))

    with op.batch_alter_table('inspections_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_officer_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lead_officer_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='The lead officer who created the inspection'))
        batch_op.drop_index(batch_op.f('ix_inspections_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspections_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspections_version_ir_number'))
        batch_op.drop_index(batch_op.f('ix_inspections_version_end_transaction_id'))
        batch_op.drop_column('primary_officer_id_mod')
        batch_op.drop_column('primary_officer_id')

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_officer_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='The lead officer who created the inspection'))
        batch_op.drop_constraint('inspection_primary_officer_id_staff_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('inspection_lead_officer_id_staff_id_fkey', 'staff_users', ['lead_officer_id'], ['id'])
        batch_op.drop_column('primary_officer_id')

    with op.batch_alter_table('inspection_unapproved_projects_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_unapproved_projects_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_unapproved_projects_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_unapproved_projects_version_end_transaction_id'))

    with op.batch_alter_table('inspection_types_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_types_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_types_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_types_version_end_transaction_id'))

    with op.batch_alter_table('inspection_type_options_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_type_options_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_type_options_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_type_options_version_end_transaction_id'))

    with op.batch_alter_table('inspection_other_attendances_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_other_attendances_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_other_attendances_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_other_attendances_version_end_transaction_id'))

    with op.batch_alter_table('inspection_officers_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_officers_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_officers_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_officers_version_end_transaction_id'))

    with op.batch_alter_table('inspection_initiation_options_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_initiation_options_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_initiation_options_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_initiation_options_version_end_transaction_id'))

    with op.batch_alter_table('inspection_firstnations_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_firstnations_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_firstnations_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_firstnations_version_end_transaction_id'))

    with op.batch_alter_table('inspection_attendance_options_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_attendance_options_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_attendance_options_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_attendance_options_version_end_transaction_id'))

    with op.batch_alter_table('inspection_attendance_mappings_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_attendance_mappings_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_attendance_mappings_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_attendance_mappings_version_end_transaction_id'))

    with op.batch_alter_table('inspection_agencies_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_agencies_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_agencies_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_agencies_version_end_transaction_id'))

    with op.batch_alter_table('continuation_reports_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_continuation_reports_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_continuation_reports_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_continuation_reports_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_continuation_reports_version_case_file_id'))
        batch_op.execute('''
        ALTER TABLE continuation_reports_version
        ALTER COLUMN context_type
        TYPE contexttypeenum USING context_type::text::contexttypeenum;
    ''')

    with op.batch_alter_table('continuation_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_continuation_reports_case_file_id'))
        batch_op.execute('''
        ALTER TABLE continuation_reports
        ALTER COLUMN context_type
        TYPE contexttypeenum USING context_type::text::contexttypeenum;
    ''')

    with op.batch_alter_table('continuation_report_keys_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_continuation_report_keys_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_continuation_report_keys_version_report_id'))
        batch_op.drop_index(batch_op.f('ix_continuation_report_keys_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_continuation_report_keys_version_end_transaction_id'))
        batch_op.execute('''
        ALTER TABLE continuation_report_keys_version
        ALTER COLUMN key_context
        TYPE contexttypeenum USING key_context::text::contexttypeenum;
    ''')

    with op.batch_alter_table('continuation_report_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_continuation_report_keys_report_id'))
        batch_op.execute('''
        ALTER TABLE continuation_report_keys
        ALTER COLUMN key_context
        TYPE contexttypeenum USING key_context::text::contexttypeenum;
    ''')

    with op.batch_alter_table('complaints_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_first_nation_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='The unique Id of the first nation if the complaint source is selected as first nation'))
        batch_op.add_column(sa.Column('source_first_nation_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lead_officer_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lead_officer_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='The lead officer who created the inspection'))
        batch_op.drop_index(batch_op.f('ix_complaints_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_complaints_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_version_complaint_number'))
        batch_op.drop_column('primary_officer_id_mod')
        batch_op.drop_column('primary_officer_id')

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_first_nation_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='The unique Id of the first nation if the complaint source is selected as first nation'))
        batch_op.add_column(sa.Column('lead_officer_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='The lead officer who created the inspection'))
        batch_op.drop_constraint('inspection_primary_officer_id_staff_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('inspection_lead_officer_id_staff_id_fkey', 'staff_users', ['lead_officer_id'], ['id'])
        batch_op.drop_column('primary_officer_id')

    with op.batch_alter_table('complaint_unapproved_projects_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_unapproved_projects_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_unapproved_projects_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_complaint_unapproved_projects_version_end_transaction_id'))

    with op.batch_alter_table('complaint_sources_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_sources_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_sources_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_complaint_sources_version_end_transaction_id'))

    with op.batch_alter_table('complaint_source_contacts_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_source_contacts_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_source_contacts_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_complaint_source_contacts_version_end_transaction_id'))

    with op.batch_alter_table('complaint_requirement_details_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_requirement_details_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_requirement_details_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_complaint_requirement_details_version_end_transaction_id'))

    with op.batch_alter_table('complaint_req_schedule_b_details_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_req_schedule_b_details_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_req_schedule_b_details_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_complaint_req_schedule_b_details_version_end_transaction_id'))

    with op.batch_alter_table('complaint_req_order_details_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_req_order_details_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_req_order_details_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_complaint_req_order_details_version_end_transaction_id'))

    with op.batch_alter_table('complaint_req_eac_details_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_req_eac_details_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_req_eac_details_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_complaint_req_eac_details_version_end_transaction_id'))

    with op.batch_alter_table('case_files_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_officer_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lead_officer_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='The lead officer who created the case file'))
        batch_op.drop_index(batch_op.f('ix_case_files_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_case_files_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_case_files_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_case_files_version_case_file_number'))
        batch_op.drop_column('primary_officer_id_mod')
        batch_op.drop_column('primary_officer_id')

    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_officer_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='The lead officer who created the case file'))
        batch_op.drop_constraint('case_files_primary_staff_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('case_files_created_staff_id_fkey', 'staff_users', ['lead_officer_id'], ['id'])
        batch_op.drop_column('primary_officer_id')

    with op.batch_alter_table('case_file_officers_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_file_officers_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_case_file_officers_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_case_file_officers_version_end_transaction_id'))

    with op.batch_alter_table('case_file_initiation_options_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_file_initiation_options_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_case_file_initiation_options_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_case_file_initiation_options_version_end_transaction_id'))

    with op.batch_alter_table('agencies_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agencies_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_agencies_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_agencies_version_end_transaction_id'))
    op.execute(f"DROP TYPE IF EXISTS contextenum")
    # ### end Alembic commands ###
