"""adding topic and req desc in complaint

Revision ID: 3270e1234eb0
Revises: c8cc683f4019
Create Date: 2025-08-01 11:28:27.125817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3270e1234eb0'
down_revision = 'c8cc683f4019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_source_description', sa.String(), nullable=True, comment='The requirement source description of the complaint'))
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True, comment='The topic of the complaint'))
        batch_op.create_foreign_key('complaints_topic_id_topics_id', 'topics', ['topic_id'], ['id'])

    with op.batch_alter_table('complaints_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_source_description', sa.String(), autoincrement=False, nullable=True, comment='The requirement source description of the complaint'))
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), autoincrement=False, nullable=True, comment='The topic of the complaint'))
        batch_op.add_column(sa.Column('requirement_source_description_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('topic_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints_version', schema=None) as batch_op:
        batch_op.drop_column('topic_id_mod')
        batch_op.drop_column('requirement_source_description_mod')
        batch_op.drop_column('topic_id')
        batch_op.drop_column('requirement_source_description')

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_constraint('complaints_topic_id_topics_id', type_='foreignkey')
        batch_op.drop_column('topic_id')
        batch_op.drop_column('requirement_source_description')

    # ### end Alembic commands ###
