"""Remove closed as note status

Revision ID: 3aa492aa47db
Revises: 91f76d883f32
Create Date: 2025-02-06 13:22:09.682441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa492aa47db'
down_revision = '91f76d883f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE inspections set inspection_status='CLOSED' WHERE inspection_status='CLOSED_AS_NOTE'")
    op.execute("UPDATE inspections_version SET inspection_status='CLOSED' WHERE inspection_status='CLOSED_AS_NOTE'")
    op.execute("""
        CREATE TYPE inspectionstatusenum_old AS ENUM ('OPEN', 'CLOSED', 'CANCELED');
    """)
    op.execute("""
        ALTER TABLE inspections 
        ALTER COLUMN inspection_status TYPE inspectionstatusenum_old 
        USING inspection_status::text::inspectionstatusenum_old;
    """)
    op.execute("""
        ALTER TABLE inspections_version
        ALTER COLUMN inspection_status TYPE inspectionstatusenum_old 
        USING inspection_status::text::inspectionstatusenum_old;
    """)
    op.execute("DROP TYPE inspectionstatusenum;")
    op.execute("ALTER TYPE inspectionstatusenum_old RENAME TO inspectionstatusenum;")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
