"""adding more number fields in source details

Revision ID: 3af167e3a79f
Revises: 47b26a21801c
Create Date: 2025-07-08 15:18:47.524447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af167e3a79f'
down_revision = '47b26a21801c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_req_source_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_title', sa.String(), nullable=True, comment='The title of the requirement source detail'))
        batch_op.add_column(sa.Column('compliance_number', sa.String(), nullable=True, comment='The optional compliance number associated with requirement sources as Compliance Agreement'))
        batch_op.add_column(sa.Column('clause_number', sa.String(), nullable=True, comment='The optional clause number associated with requirement sources as Exemption Order'))
        batch_op.add_column(sa.Column('regulation_number', sa.String(), nullable=True, comment='The optional regulation number associated with requirement sources as Regulation'))
        batch_op.add_column(sa.Column('exemption_order_number', sa.String(), nullable=True, comment='The optional exemption order number associated with requirement sources as Exemption Order'))

    with op.batch_alter_table('inspection_req_source_details_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_title', sa.String(), autoincrement=False, nullable=True, comment='The title of the requirement source detail'))
        batch_op.add_column(sa.Column('compliance_number', sa.String(), autoincrement=False, nullable=True, comment='The optional compliance number associated with requirement sources as Compliance Agreement'))
        batch_op.add_column(sa.Column('clause_number', sa.String(), autoincrement=False, nullable=True, comment='The optional clause number associated with requirement sources as Exemption Order'))
        batch_op.add_column(sa.Column('regulation_number', sa.String(), autoincrement=False, nullable=True, comment='The optional regulation number associated with requirement sources as Regulation'))
        batch_op.add_column(sa.Column('exemption_order_number', sa.String(), autoincrement=False, nullable=True, comment='The optional exemption order number associated with requirement sources as Exemption Order'))
        batch_op.add_column(sa.Column('source_title_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('compliance_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('clause_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('regulation_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('exemption_order_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('requirement_sources', schema=None) as batch_op:
        batch_op.alter_column('source_title',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='The title of the requirement source')

    with op.batch_alter_table('requirement_sources_version', schema=None) as batch_op:
        batch_op.alter_column('source_title_mod',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_sources_version', schema=None) as batch_op:
        batch_op.alter_column('source_title_mod',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('requirement_sources', schema=None) as batch_op:
        batch_op.alter_column('source_title',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='The title of the requirement source')

    with op.batch_alter_table('inspection_req_source_details_version', schema=None) as batch_op:
        batch_op.drop_column('exemption_order_number_mod')
        batch_op.drop_column('regulation_number_mod')
        batch_op.drop_column('clause_number_mod')
        batch_op.drop_column('compliance_number_mod')
        batch_op.drop_column('source_title_mod')
        batch_op.drop_column('exemption_order_number')
        batch_op.drop_column('regulation_number')
        batch_op.drop_column('clause_number')
        batch_op.drop_column('compliance_number')
        batch_op.drop_column('source_title')

    with op.batch_alter_table('inspection_req_source_details', schema=None) as batch_op:
        batch_op.drop_column('exemption_order_number')
        batch_op.drop_column('regulation_number')
        batch_op.drop_column('clause_number')
        batch_op.drop_column('compliance_number')
        batch_op.drop_column('source_title')

    # ### end Alembic commands ###
