"""removing inspection_req_detail_image unique index

Revision ID: 3d9e96992c02
Revises: e6d2d06d4b65
Create Date: 2025-10-15 12:58:09.415778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9e96992c02'
down_revision = 'e6d2d06d4b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_req_detail_images', schema=None) as batch_op:
        batch_op.drop_index('unique_non_deleted_req_detail_original_file_name', postgresql_where='(is_deleted = false)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_req_detail_images', schema=None) as batch_op:
        batch_op.create_index('unique_non_deleted_req_detail_original_file_name', ['req_detail_id', 'original_file_name'], unique=True, postgresql_where='(is_deleted = false)')

    # ### end Alembic commands ###
