"""adding progress column warning letter

Revision ID: 3e71292c2eaf
Revises: 970586edecc4
Create Date: 2025-05-28 17:18:35.757384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e71292c2eaf'
down_revision = '970586edecc4'
branch_labels = None
depends_on = None


def upgrade():
    warningletterprogressenum = sa.Enum('DRAFTING', 'DEPUTY_REVIEW', 'APPROVED', 'ISSUED', name='warningletterprogressenum')
    warningletterprogressenum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warning_letters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', warningletterprogressenum, nullable=True, comment='Progress of the warning letter'))

    with op.batch_alter_table('warning_letters_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Enum('DRAFTING', 'DEPUTY_REVIEW', 'APPROVED', 'ISSUED', name='warningletterprogressenum'), autoincrement=False, nullable=True, comment='Progress of the warning letter'))
        batch_op.add_column(sa.Column('progress_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warning_letters_version', schema=None) as batch_op:
        batch_op.drop_column('progress_mod')
        batch_op.drop_column('progress')

    with op.batch_alter_table('warning_letters', schema=None) as batch_op:
        batch_op.drop_column('progress')
    op.execute('DROP TYPE warningletterprogressenum')

    # ### end Alembic commands ###
