"""violation_ticket status change

Revision ID: 40adc38e9a22
Revises: a4c0c836847b
Create Date: 2025-09-29 13:56:25.386607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40adc38e9a22'
down_revision = 'a4c0c836847b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE violationticketstatusenum ADD VALUE 'DEEMED_GUILTY'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the current enum to backup
    op.execute("ALTER TYPE violationticketstatusenum RENAME TO violationticketstatusenum_old")
    # Create new enum without DEEMED_GUILTY
    op.execute("CREATE TYPE violationticketstatusenum AS ENUM('ISSUED', 'PAID', 'DISPUTED')")
    # Update the main table column to use the new enum
    op.execute("""
        ALTER TABLE violation_tickets
        ALTER COLUMN status
        TYPE violationticketstatusenum
        USING status::text::violationticketstatusenum
    """)
    # Update the version table column to use the new enum
    op.execute("""
        ALTER TABLE violation_tickets_version
        ALTER COLUMN status
        TYPE violationticketstatusenum
        USING status::text::violationticketstatusenum
    """)
    # Drop the old enum
    op.execute("DROP TYPE violationticketstatusenum_old")
    # ### end Alembic commands ###
