"""add Other to initiation

Revision ID: 452a69254b48
Revises: 1637128b4b97
Create Date: 2025-07-03 15:24:02.193483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452a69254b48'
down_revision = '1637128b4b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First get the next id value from the sequence
    op.execute("SELECT setval('case_file_initiation_options_id_seq', 2, true);")
    op.execute("""
        INSERT INTO case_file_initiation_options (
            id,
            name,
            sort_order,
            created_date,
            created_by
        ) VALUES (
            nextval('case_file_initiation_options_id_seq'),
            'Other',
            4,
            now(),
            'system'
        )
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM case_file_initiation_options WHERE name = 'Other'")
    # ### end Alembic commands ###
