"""ir_status_removed_debrief_date_added

Revision ID: 4dd4d28f1914
Revises: 6e1dd95e1a4d
Create Date: 2025-03-04 14:05:18.882604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd4d28f1914'
down_revision = '6e1dd95e1a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debrief_date', sa.DateTime(timezone=True), nullable=True, comment='The debrief date of the inspection'))
        batch_op.drop_constraint('inspection_ir_status_id_ir_status_options_id_fkey', type_='foreignkey')
        batch_op.drop_column('ir_status_id')

    with op.batch_alter_table('inspections_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debrief_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='The debrief date of the inspection'))
        batch_op.add_column(sa.Column('debrief_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.drop_column('ir_status_id_mod')
        batch_op.drop_column('ir_status_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ir_status_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ir_status_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_column('debrief_date_mod')
        batch_op.drop_column('debrief_date')

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ir_status_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('inspection_ir_status_id_ir_status_options_id_fkey', 'ir_status_options', ['ir_status_id'], ['id'])
        batch_op.drop_column('debrief_date')

    # ### end Alembic commands ###
