"""add natural sort function

Revision ID: 4f4bb8744a2a
Revises: 6edfa48316d0
Create Date: 2025-08-11 11:38:43.820784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4bb8744a2a'
down_revision = '6edfa48316d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add natural sort function
    op.execute("""
        CREATE OR REPLACE FUNCTION public.natural_sort_key(t text)
         RETURNS text
         LANGUAGE sql
         IMMUTABLE
        AS $function$
        WITH cleaned AS (
          SELECT NULLIF(trim(t), '') AS val  -- treat empty strings as NULL
        ),
        parts AS (
          SELECT unnest(regexp_matches(val, '([0-9]+|[^0-9]+)', 'g')) AS part
          FROM cleaned
        )
        SELECT string_agg(
                 CASE
                   WHEN part ~ '^[0-9]+$' THEN lpad(part, 10, '0')
                   ELSE lower(part)
                 END,
                 ''
               )
        FROM parts;
        $function$;
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop natural sort function
    op.execute("DROP FUNCTION IF EXISTS public.natural_sort_key(text);")

    # ### end Alembic commands ###
