"""inspection requirements

Revision ID: 50caf15789a6
Revises: e2f642264b01
Create Date: 2024-12-20 13:34:47.598795

"""

from alembic import op
from datetime import datetime
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "50caf15789a6"
down_revision = "e2f642264b01"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    compliance_finding_table = op.create_table(
        "compliance_finding_options",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="The unique identifier of the option",
        ),
        sa.Column("name", sa.String(), nullable=True, comment="The name of the option"),
        sa.Column(
            "sort_order",
            sa.Integer(),
            nullable=True,
            comment="Order of priority. Mainly used order the options while listing",
        ),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="t", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="f", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "compliance_finding_options_version",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="The unique identifier of the option",
        ),
        sa.Column(
            "name",
            sa.String(),
            autoincrement=False,
            nullable=True,
            comment="The name of the option",
        ),
        sa.Column(
            "sort_order",
            sa.Integer(),
            autoincrement=False,
            nullable=True,
            comment="Order of priority. Mainly used order the options while listing",
        ),
        sa.Column("created_date", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_date", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "created_by", sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_by", sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="t",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default="f",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.Column(
            "name_mod", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "sort_order_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_date_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "updated_date_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_by_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "updated_by_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_active_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_deleted_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    with op.batch_alter_table(
        "compliance_finding_options_version", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_compliance_finding_options_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_compliance_finding_options_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_compliance_finding_options_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    enforcement_action_table = op.create_table(
        "enforcement_action_options",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="The unique identifier of the option",
        ),
        sa.Column("name", sa.String(), nullable=True, comment="The name of the option"),
        sa.Column(
            "sort_order",
            sa.Integer(),
            nullable=True,
            comment="Order of priority. Mainly used order the options while listing",
        ),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="t", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="f", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "enforcement_action_options_version",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="The unique identifier of the option",
        ),
        sa.Column(
            "name",
            sa.String(),
            autoincrement=False,
            nullable=True,
            comment="The name of the option",
        ),
        sa.Column(
            "sort_order",
            sa.Integer(),
            autoincrement=False,
            nullable=True,
            comment="Order of priority. Mainly used order the options while listing",
        ),
        sa.Column("created_date", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_date", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "created_by", sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_by", sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="t",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default="f",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.Column(
            "name_mod", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "sort_order_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_date_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "updated_date_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_by_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "updated_by_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_active_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_deleted_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    with op.batch_alter_table(
        "enforcement_action_options_version", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_enforcement_action_options_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_enforcement_action_options_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_enforcement_action_options_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    op.create_table(
        "inspection_requirements_version",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="The unique identifier",
        ),
        sa.Column(
            "inspection_id",
            sa.Integer(),
            autoincrement=False,
            nullable=True,
            comment="The unique identifier of the inspection",
        ),
        sa.Column(
            "summary",
            sa.String(),
            autoincrement=False,
            nullable=True,
            comment="The summary of the requirement",
        ),
        sa.Column(
            "topic_id",
            sa.Integer(),
            autoincrement=False,
            nullable=True,
            comment="The topic of the requirement",
        ),
        sa.Column(
            "enforcement_action_id",
            sa.Integer(),
            autoincrement=False,
            nullable=True,
            comment="The enforcement action taken on the requirement",
        ),
        sa.Column(
            "compliance_finding_id",
            sa.Integer(),
            autoincrement=False,
            nullable=True,
            comment="Compliance finding of the requirement",
        ),
        sa.Column(
            "findings",
            sa.String(),
            autoincrement=False,
            nullable=True,
            comment="The findings of the requirement",
        ),
        sa.Column("created_date", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_date", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "created_by", sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_by", sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="t",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default="f",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.Column(
            "inspection_id_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "summary_mod", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "topic_id_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "enforcement_action_id_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "compliance_finding_id_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "findings_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_date_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "updated_date_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_by_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "updated_by_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_active_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_deleted_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    with op.batch_alter_table(
        "inspection_requirements_version", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inspection_requirements_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inspection_requirements_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inspection_requirements_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    op.create_table(
        "inspection_requirements",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="The unique identifier",
        ),
        sa.Column(
            "inspection_id",
            sa.Integer(),
            nullable=False,
            comment="The unique identifier of the inspection",
        ),
        sa.Column(
            "summary",
            sa.String(),
            nullable=False,
            comment="The summary of the requirement",
        ),
        sa.Column(
            "topic_id",
            sa.Integer(),
            nullable=False,
            comment="The topic of the requirement",
        ),
        sa.Column(
            "enforcement_action_id",
            sa.Integer(),
            nullable=False,
            comment="The enforcement action taken on the requirement",
        ),
        sa.Column(
            "compliance_finding_id",
            sa.Integer(),
            nullable=False,
            comment="Compliance finding of the requirement",
        ),
        sa.Column(
            "findings",
            sa.String(),
            nullable=True,
            comment="The findings of the requirement",
        ),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="t", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="f", nullable=False),
        sa.ForeignKeyConstraint(
            ["compliance_finding_id"],
            ["compliance_finding_options.id"],
            name="inspection_req_compliance_finding_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["enforcement_action_id"],
            ["enforcement_action_options.id"],
            name="insepction_requirements_enforcement_action_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name="inspection_requirements_inspection_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name="inspection_requirements_topic_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    compliance_findings = [
        {
            "name": "In",
            "sort_order": 1,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
        {
            "name": "Out",
            "sort_order": 2,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
        {
            "name": "Not Determined",
            "sort_order": 3,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
    ]
    op.bulk_insert(
        compliance_finding_table,
        compliance_findings,
    )
    enforcement_actions = [
        {
            "name": "To Be Determined",
            "sort_order": 1,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
        {
            "name": "Not Applicable",
            "sort_order": 2,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
        {
            "name": "Notice of Non-Compliance",
            "sort_order": 3,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
        {
            "name": "Warning Letter",
            "sort_order": 4,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
        {
            "name": "Order",
            "sort_order": 5,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
        {
            "name": "Referral to Administrative Penalty",
            "sort_order": 6,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
        {
            "name": "Referral to Another Agency",
            "sort_order": 7,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
        {
            "name": "Violation Ticket",
            "sort_order": 8,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
        {
            "name": "Prosecution Recommendation",
            "sort_order": 9,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
    ]
    op.bulk_insert(enforcement_action_table, enforcement_actions)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inspection_requirements")
    with op.batch_alter_table(
        "inspection_requirements_version", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_inspection_requirements_version_transaction_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_inspection_requirements_version_operation_type")
        )
        batch_op.drop_index(
            batch_op.f("ix_inspection_requirements_version_end_transaction_id")
        )

    op.drop_table("inspection_requirements_version")
    with op.batch_alter_table(
        "enforcement_action_options_version", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_enforcement_action_options_version_transaction_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_enforcement_action_options_version_operation_type")
        )
        batch_op.drop_index(
            batch_op.f("ix_enforcement_action_options_version_end_transaction_id")
        )

    op.drop_table("enforcement_action_options_version")
    op.drop_table("enforcement_action_options")
    with op.batch_alter_table(
        "compliance_finding_options_version", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_compliance_finding_options_version_transaction_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_compliance_finding_options_version_operation_type")
        )
        batch_op.drop_index(
            batch_op.f("ix_compliance_finding_options_version_end_transaction_id")
        )

    op.drop_table("compliance_finding_options_version")
    op.drop_table("compliance_finding_options")
    # ### end Alembic commands ###
