"""adding description to complaint source contact

Revision ID: 583a92eaa5f1
Revises: a37ed457f4cb
Create Date: 2024-09-25 13:14:27.200485

"""

from alembic import op
import sqlalchemy as sa
from compliance_api.models.type import EncryptedType

# revision identifiers, used by Alembic.
revision = "583a92eaa5f1"
down_revision = "a37ed457f4cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("complaint_source_contact", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "description",
                EncryptedType(),
                nullable=True,
                comment="Any description about the contact",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("complaint_source_contact", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
