"""staff and position tables

Revision ID: 5c3d1411be77
Revises: 20bcb68bc2ac
Create Date: 2024-08-02 14:27:42.565023

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c3d1411be77"
down_revision = "20bcb68bc2ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    position_table = op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="t", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="f", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("staff_users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("position_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("deputy_director_id", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("supervisor_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("auth_user_guid", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("is_active", sa.Boolean(), server_default="t", nullable=False)
        )
        batch_op.add_column(
            sa.Column("is_deleted", sa.Boolean(), server_default="f", nullable=False)
        )
        batch_op.alter_column(
            "created_by",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=100),
            nullable=False,
        )
        batch_op.alter_column(
            "updated_by",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=100),
            existing_nullable=True,
        )
        batch_op.drop_index("ix_staff_users_username")
        batch_op.create_index(
            batch_op.f("ix_staff_users_auth_user_guid"), ["auth_user_guid"], unique=True
        )
        batch_op.create_foreign_key(
            "staff_users_deputy_director_id_fkey",
            "staff_users",
            ["deputy_director_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "staff_users_position_id_fkey", "positions", ["position_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "staff_users_supervisor_id_fkey", "staff_users", ["supervisor_id"], ["id"]
        )
        batch_op.drop_column("contact_number")
        batch_op.drop_column("username")
        batch_op.drop_column("email_address")
        batch_op.drop_column("middle_name")
    op.bulk_insert(
        position_table,
        [
            {
                "name": "Compliance & Enforcement Officer",
                "description": "Compliance and Enforcement Officer Position",
                "created_date": datetime.utcnow(),
                "created_by": "system",  # Or replace with the actual creator
            },
            {
                "name": "Senior Compliance & Enforcement Officer",
                "description": "Senior Compliance and Enforcement Officer Position",
                "created_date": datetime.utcnow(),
                "created_by": "system",  # Or replace with the actual creator
            },
            {
                "name": "Deputy Director Operations",
                "description": "Deputy Director Operations Position",
                "created_date": datetime.utcnow(),
                "created_by": "system",  # Or replace with the actual creator
            },
            {
                "name": "Director",
                "description": "Director Position",
                "created_date": datetime.utcnow(),
                "created_by": "system",  # Or replace with the actual creator
            },
        ],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("staff_users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "middle_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "email_address",
                sa.VARCHAR(length=100),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "username", sa.VARCHAR(length=100), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "contact_number",
                sa.VARCHAR(length=50),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_constraint("staff_users_supervisor_id_fkey", type_="foreignkey")
        batch_op.drop_constraint("staff_users_position_id_fkey", type_="foreignkey")
        batch_op.drop_constraint(
            "staff_users_deputy_director_id_fkey", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_staff_users_auth_user_guid"))
        batch_op.create_index("ix_staff_users_username", ["username"], unique=True)
        batch_op.alter_column(
            "updated_by",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_by",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=50),
            nullable=True,
        )
        batch_op.drop_column("is_deleted")
        batch_op.drop_column("is_active")
        batch_op.drop_column("auth_user_guid")
        batch_op.drop_column("supervisor_id")
        batch_op.drop_column("deputy_director_id")
        batch_op.drop_column("position_id")

    op.drop_table("positions")
    # ### end Alembic commands ###
