"""enforcement action option label change

Revision ID: 6b4b766bd2a3
Revises: 3af167e3a79f
Create Date: 2025-07-16 14:50:52.643683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4b766bd2a3'
down_revision = '3af167e3a79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE enforcement_action_options SET name = 'Administrative Penalty Recommendation' WHERE name = 'Referral to Administrative Penalty'")
    op.execute("UPDATE enforcement_action_options SET name = 'Charge Recommendation' WHERE name = 'Prosecution Recommendation'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE enforcement_action_options SET name = 'Referral to Administrative Penalty' WHERE name = 'Administrative Penalty Recommendation'")
    op.execute("UPDATE enforcement_action_options SET name = 'Prosecution Recommendation' WHERE name = 'Charge Recommendation'")
    # ### end Alembic commands ###
