"""inspection_requirement_patches

Revision ID: 6c3b6755e2dc
Revises: a684c47ac3e8
Create Date: 2025-01-02 18:17:21.124175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3b6755e2dc'
down_revision = 'a684c47ac3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_req_detail_documents', schema=None) as batch_op:
        batch_op.alter_column('document_title',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='The title of the document')

    with op.batch_alter_table('inspection_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False, comment='The order of requirements'))
        batch_op.alter_column('enforcement_action_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='The enforcement action taken on the requirement')
        batch_op.alter_column('compliance_finding_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Compliance finding of the requirement')
        batch_op.create_index(batch_op.f('ix_inspection_requirements_inspection_id'), ['inspection_id'], unique=False)

    with op.batch_alter_table('inspection_requirements_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), autoincrement=False, nullable=True, comment='The order of requirements'))
        batch_op.add_column(sa.Column('sort_order_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.create_index(batch_op.f('ix_inspection_requirements_version_inspection_id'), ['inspection_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_requirements_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_requirements_version_inspection_id'))
        batch_op.drop_column('sort_order_mod')
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('inspection_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_requirements_inspection_id'))
        batch_op.alter_column('compliance_finding_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Compliance finding of the requirement')
        batch_op.alter_column('enforcement_action_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='The enforcement action taken on the requirement')
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('inspection_req_detail_documents', schema=None) as batch_op:
        batch_op.alter_column('document_title',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='The title of the document')

    # ### end Alembic commands ###
