"""appendix-fkey-inspection added


Revision ID: 6e1dd95e1a4d
Revises: e8a29d9b9a0d
Create Date: 2025-02-26 11:43:42.768435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1dd95e1a4d'
down_revision = 'e8a29d9b9a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appendices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspection_id', sa.Integer(), nullable=False, comment='The unique identifier of the inspection'))
        batch_op.drop_constraint('appendices_appendix_no_key', type_='unique')
        batch_op.create_index('unique_non_deleted_appendix_number', ['inspection_id', 'appendix_no'], unique=True, postgresql_where=sa.text('is_deleted = false'))
        batch_op.create_foreign_key('appendix_inspection_id_inspection_id_fkey', 'inspections', ['inspection_id'], ['id'])

    with op.batch_alter_table('appendices_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspection_id', sa.Integer(), autoincrement=False, nullable=True, comment='The unique identifier of the inspection'))
        batch_op.add_column(sa.Column('inspection_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appendices_version', schema=None) as batch_op:
        batch_op.drop_column('inspection_id_mod')
        batch_op.drop_column('inspection_id')

    with op.batch_alter_table('appendices', schema=None) as batch_op:
        batch_op.drop_constraint('appendix_inspection_id_inspection_id_fkey', type_='foreignkey')
        batch_op.drop_index('unique_non_deleted_appendix_number', postgresql_where=sa.text('is_deleted = false'))
        batch_op.create_unique_constraint('appendices_appendix_no_key', ['appendix_no'])
        batch_op.drop_column('inspection_id')

    # ### end Alembic commands ###
