"""update the requirement source source title

Revision ID: 6edfa48316d0
Revises: 94d773680c08
Create Date: 2025-08-11 09:54:14.903883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edfa48316d0'
down_revision = '94d773680c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE requirement_sources SET source_title = '${eac_type} # ${eac#} Schedule B - Table of Conditions' WHERE id = 1")
    op.execute("UPDATE requirement_sources SET source_title = '${eac_type} # ${eac#} Schedule A - Certified Project Description' WHERE id = 4")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE requirement_sources SET source_title = 'EAC# ${eac#} Schedule B - Table of Conditions' WHERE id = 1")
    op.execute("UPDATE requirement_sources SET source_title = 'EAC# ${eac#} Schedule A - Certified Project Description' WHERE id = 4")

    # ### end Alembic commands ###
