"""new_colum removed

Revision ID: 70beb2d53c21
Revises: a179cda47b84
Create Date: 2025-03-24 11:51:02.011387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70beb2d53c21'
down_revision = 'a179cda47b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('new_column')

    with op.batch_alter_table('topics_version', schema=None) as batch_op:
        batch_op.drop_column('new_column')
        batch_op.drop_column('new_column_mod')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_column_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('new_column', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_column', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
