"""case file tables

Revision ID: 774870c99c95
Revises: f9a414e34ea4
Create Date: 2024-08-15 15:54:35.140278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774870c99c95'
down_revision = 'f9a414e34ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier of the case file'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='The unique identifier of the project associated with the case file'),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False, comment='The date on which the case file is created'),
    sa.Column('lead_officer_id', sa.Integer(), nullable=True),
    sa.Column('initiation', sa.Enum('INSPECTION', 'COMPLAINT', name='casefileinitiationenum'), nullable=False, comment='Case file initiation options'),
    sa.Column('case_file_number', sa.Integer(), nullable=False, comment='The unique case file number'),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['lead_officer_id'], ['staff_users.id'], name='case_files_created_staff_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_files_case_file_number'), ['case_file_number'], unique=True)

    op.create_table('case_file_officers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier of the case file officers'),
    sa.Column('case_file_id', sa.Integer(), nullable=False, comment='The unique identifier of the associated case file'),
    sa.Column('officer_id', sa.Integer(), nullable=False, comment='The unique identifier of the associated staff user'),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], name='case_file_officers_case_files_id_fkey'),
    sa.ForeignKeyConstraint(['officer_id'], ['staff_users.id'], name='case_file_officers_staff_users_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_file_officers')
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_files_case_file_number'))

    op.drop_table('case_files')
    # ### end Alembic commands ###
