"""inspection_requirement patches

Revision ID: 791cc75df1c4
Revises: a684c47ac3e8
Create Date: 2025-01-02 15:02:27.066126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791cc75df1c4'
down_revision = 'a684c47ac3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_req_detail_documents', schema=None) as batch_op:
        batch_op.alter_column('document_title',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='The title of the document')

    with op.batch_alter_table('inspection_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False, comment='The order of requirements'))
        batch_op.alter_column('enforcement_action_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='The enforcement action taken on the requirement')
        batch_op.alter_column('compliance_finding_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Compliance finding of the requirement')

    with op.batch_alter_table('inspection_requirements_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), autoincrement=False, nullable=True, comment='The order of requirements'))
        batch_op.add_column(sa.Column('sort_order_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_requirements_version', schema=None) as batch_op:
        batch_op.drop_column('sort_order_mod')
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('inspection_requirements', schema=None) as batch_op:
        batch_op.alter_column('compliance_finding_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Compliance finding of the requirement')
        batch_op.alter_column('enforcement_action_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='The enforcement action taken on the requirement')
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('inspection_req_detail_documents', schema=None) as batch_op:
        batch_op.alter_column('document_title',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='The title of the document')

    # ### end Alembic commands ###
