"""added title in complaint contact

Revision ID: 7a8b9c0d1e2f
Revises: 5b2cf0e48b48
Create Date: 2024-12-19 10:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from compliance_api.models.type import EncryptedType

# revision identifiers, used by Alembic.
revision = "7a8b9c0d1e2f"
down_revision = "6edfa48316d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add title column to main table
    with op.batch_alter_table("complaint_source_contacts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "title",
                EncryptedType(),
                nullable=True,
                comment="The title of the contact person",
            )
        )

    # Add title column to version table
    with op.batch_alter_table("complaint_source_contacts_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "title",
                EncryptedType(),
                nullable=True,
                comment="The title of the contact person",
            )
        )
        batch_op.add_column(
            sa.Column(
                "title_mod",
                sa.Boolean(),
                nullable=True,
                comment="Modification flag for title field",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove title column from version table
    with op.batch_alter_table("complaint_source_contacts_version", schema=None) as batch_op:
        batch_op.drop_column("title_mod")
        batch_op.drop_column("title")

    # Remove title column from main table
    with op.batch_alter_table("complaint_source_contacts", schema=None) as batch_op:
        batch_op.drop_column("title")

    # ### end Alembic commands ###
