"""change_info_inspection_records

Revision ID: 80afcd35ad35
Revises: e85b901b6ba6
Create Date: 2025-03-19 10:50:46.569040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80afcd35ad35'
down_revision = 'e85b901b6ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_record_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True, comment='The approved date'))

    with op.batch_alter_table('inspection_record_approvals_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='The approved date'))
        batch_op.add_column(sa.Column('approved_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_change_info', sa.JSON(), nullable=True, comment='To indicate if selected fields have changed or not'))

    with op.batch_alter_table('inspection_records_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_change_info', sa.JSON(), autoincrement=False, nullable=True, comment='To indicate if selected fields have changed or not'))
        batch_op.add_column(sa.Column('field_change_info_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_records_version', schema=None) as batch_op:
        batch_op.drop_column('field_change_info_mod')
        batch_op.drop_column('field_change_info')

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.drop_column('field_change_info')

    with op.batch_alter_table('inspection_record_approvals_version', schema=None) as batch_op:
        batch_op.drop_column('approved_date_mod')
        batch_op.drop_column('approved_date')

    with op.batch_alter_table('inspection_record_approvals', schema=None) as batch_op:
        batch_op.drop_column('approved_date')

    # ### end Alembic commands ###
