"""inspection requirement chagne for regulatory considerations

Revision ID: 88ed0885be9e
Revises: c42e6b5815dd
Create Date: 2025-01-29 21:22:17.966961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ed0885be9e'
down_revision = 'c42e6b5815dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    inspectionrequirementtypeenum = sa.Enum('REQ', 'REG', name='inspectionrequirementtypeenum')
    inspectionrequirementtypeenum.create(op.get_bind())
    with op.batch_alter_table('inspection_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_id', sa.Integer(), nullable=True, comment='Associated agency if the type is regulatory consideration'))
        batch_op.add_column(sa.Column('req_type', sa.Enum('REQ', 'REG', name='inspectionrequirementtypeenum'), nullable=True))
        batch_op.create_foreign_key('inspection_req_agency_id', 'agencies', ['agency_id'], ['id'])

    with op.batch_alter_table('inspection_requirements_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_id', sa.Integer(), autoincrement=False, nullable=True, comment='Associated agency if the type is regulatory consideration'))
        batch_op.add_column(sa.Column('req_type', sa.Enum('REQ', 'REG', name='inspectionrequirementtypeenum'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('agency_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('req_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.execute("UPDATE inspection_requirements SET req_type='REQ'")
    op.alter_column('inspection_requirements', 'req_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_requirements_version', schema=None) as batch_op:
        batch_op.drop_column('req_type_mod')
        batch_op.drop_column('agency_id_mod')
        batch_op.drop_column('req_type')
        batch_op.drop_column('agency_id')

    with op.batch_alter_table('inspection_requirements', schema=None) as batch_op:
        batch_op.drop_constraint('inspection_req_agency_id', type_='foreignkey')
        batch_op.drop_column('req_type')
        batch_op.drop_column('agency_id')

    # ### end Alembic commands ###
