"""add complaint resolutions table

Revision ID: 8b9c0d1e2f1a
Revises: 7a8b9c0d1e2f
Create Date: 2024-12-20 14:00:00.000000

"""

from alembic import op
from datetime import datetime
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b9c0d1e2f1a"
down_revision = "7a8b9c0d1e2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    complaint_resolution_table = op.create_table(
        "complaint_resolutions",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="The unique identifier of the resolution option",
        ),
        sa.Column("name", sa.String(), nullable=True, comment="The name of the resolution option"),
        sa.Column(
            "sort_order",
            sa.Integer(),
            nullable=True,
            comment="Order of priority. Mainly used order the options while listing",
        ),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="t", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="f", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "complaint_resolutions_version",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="The unique identifier of the resolution option",
        ),
        sa.Column(
            "name",
            sa.String(),
            autoincrement=False,
            nullable=True,
            comment="The name of the resolution option",
        ),
        sa.Column(
            "sort_order",
            sa.Integer(),
            autoincrement=False,
            nullable=True,
            comment="Order of priority. Mainly used order the options while listing",
        ),
        sa.Column("created_date", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_date", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "created_by", sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_by", sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="t",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default="f",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.Column(
            "name_mod", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "sort_order_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_date_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "updated_date_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_by_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "updated_by_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_active_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_deleted_mod",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    with op.batch_alter_table(
        "complaint_resolutions_version", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_complaint_resolutions_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_complaint_resolutions_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_complaint_resolutions_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    # Insert seed data
    complaint_resolutions = [
        {
            "name": "Inspection / Investigation",
            "sort_order": 1,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
        {
            "name": "Referred to Agency",
            "sort_order": 2,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
        {
            "name": "Unfounded",
            "sort_order": 3,
            "created_date": datetime.utcnow(),
            "created_by": "system",
            "is_active": True,
            "is_deleted": False,
        },
    ]
    op.bulk_insert(
        complaint_resolution_table,
        complaint_resolutions,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "complaint_resolutions_version", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_complaint_resolutions_version_transaction_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_complaint_resolutions_version_operation_type")
        )
        batch_op.drop_index(
            batch_op.f("ix_complaint_resolutions_version_end_transaction_id")
        )

    op.drop_table("complaint_resolutions_version")
    op.drop_table("complaint_resolutions")
    # ### end Alembic commands ###
