"""violation ticket tables

Revision ID: 8e9ac9d6e233
Revises: 4f4bb8744a2a
Create Date: 2025-08-11 14:40:54.861955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9ac9d6e233'
down_revision = '4f4bb8744a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation_ticket_inspection_requirement_maps_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('violation_ticket_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('inspection_requirement_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('violation_ticket_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inspection_requirement_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('violation_ticket_inspection_requirement_maps_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violation_ticket_inspection_requirement_maps_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_ticket_inspection_requirement_maps_version_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_ticket_inspection_requirement_maps_version_operation_type'), ['operation_type'], unique=False)

    op.create_table('violation_tickets_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('vt_number', sa.String(), autoincrement=False, nullable=True, comment='System generated VT number'),
    sa.Column('date_issued', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='Date the ticket was issued'),
    sa.Column('ticket_number', sa.String(), autoincrement=False, nullable=True, comment='Manual ticket number'),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), autoincrement=False, nullable=True, comment='Fine amount'),
    sa.Column('status', sa.Enum('ISSUED', 'PAID', 'DISPUTED', name='violationticketstatusenum'), autoincrement=False, nullable=True, comment='Ticket status'),
    sa.Column('status_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='Status date'),
    sa.Column('inspection_id', sa.Integer(), autoincrement=False, nullable=True, comment='Associated inspection'),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('vt_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_issued_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ticket_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fine_amount_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inspection_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('violation_tickets_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violation_tickets_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_tickets_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_tickets_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('violation_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('vt_number', sa.String(), nullable=False, comment='System generated VT number'),
    sa.Column('date_issued', sa.DateTime(timezone=True), nullable=False, comment='Date the ticket was issued'),
    sa.Column('ticket_number', sa.String(), nullable=False, comment='Manual ticket number'),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Fine amount'),
    sa.Column('status', sa.Enum('ISSUED', 'PAID', 'DISPUTED', name='violationticketstatusenum'), nullable=False, comment='Ticket status'),
    sa.Column('status_date', sa.DateTime(timezone=True), nullable=False, comment='Status date'),
    sa.Column('inspection_id', sa.Integer(), nullable=False, comment='Associated inspection'),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violation_tickets', schema=None) as batch_op:
        batch_op.create_index('unique_non_deleted_ticket_number', ['ticket_number'], unique=True, postgresql_where=False)
        batch_op.create_index('unique_non_deleted_vt_number', ['vt_number'], unique=True, postgresql_where=False)

    op.create_table('violation_ticket_inspection_requirement_maps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('violation_ticket_id', sa.Integer(), nullable=True),
    sa.Column('inspection_requirement_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['inspection_requirement_id'], ['inspection_requirements.id'], name='vt_inspection_map_requirement_id_fkey'),
    sa.ForeignKeyConstraint(['violation_ticket_id'], ['violation_tickets.id'], name='vt_inspection_map_vt_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation_ticket_inspection_requirement_maps')
    with op.batch_alter_table('violation_tickets', schema=None) as batch_op:
        batch_op.drop_index('unique_non_deleted_vt_number', postgresql_where=False)
        batch_op.drop_index('unique_non_deleted_ticket_number', postgresql_where=False)

    op.drop_table('violation_tickets')
    with op.batch_alter_table('violation_tickets_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violation_tickets_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_violation_tickets_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_violation_tickets_version_end_transaction_id'))

    op.drop_table('violation_tickets_version')
    with op.batch_alter_table('violation_ticket_inspection_requirement_maps_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violation_ticket_inspection_requirement_maps_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_violation_ticket_inspection_requirement_maps_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_violation_ticket_inspection_requirement_maps_version_end_transaction_id'))

    op.drop_table('violation_ticket_inspection_requirement_maps_version')
    op.execute("DROP TYPE violationticketstatusenum")
    # ### end Alembic commands ###
