"""adding order_id to requirement source

Revision ID: 9058b76354e0
Revises: 3e71292c2eaf
Create Date: 2025-05-30 11:04:09.969949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9058b76354e0'
down_revision = '3e71292c2eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_req_source_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True, comment='The order id associated with selected order as requirement source'))
        batch_op.create_foreign_key('inspection_req_detail_order_id_fkey', 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('inspection_req_source_details_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), autoincrement=False, nullable=True, comment='The order id associated with selected order as requirement source'))
        batch_op.add_column(sa.Column('order_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_req_source_details_version', schema=None) as batch_op:
        batch_op.drop_column('order_id_mod')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('inspection_req_source_details', schema=None) as batch_op:
        batch_op.drop_constraint('inspection_req_detail_order_id_fkey', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
