"""Unique key for req_doc_details

Revision ID: 94d773680c08
Revises: c8ca64602ac4
Create Date: 2025-08-11 07:04:17.947584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d773680c08'
down_revision = 'c8ca64602ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_req_order_details', schema=None) as batch_op:
        batch_op.alter_column('complaint_id',
               existing_type=sa.INTEGER(),
               comment='The unique id of the complaint',
               existing_nullable=False)

    with op.batch_alter_table('complaint_req_order_details_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_req_order_details_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_req_order_details_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_req_order_details_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inspection_req_detail_documents', schema=None) as batch_op:
        batch_op.create_index('unique_non_deleted_req_detail_document_title', ['req_detail_id', 'document_title'], unique=True, postgresql_where=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_req_detail_documents', schema=None) as batch_op:
        batch_op.drop_index('unique_non_deleted_req_detail_document_title', postgresql_where=False)

    with op.batch_alter_table('complaint_req_order_details_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_req_order_details_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_req_order_details_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_complaint_req_order_details_version_end_transaction_id'))

    with op.batch_alter_table('complaint_req_order_details', schema=None) as batch_op:
        batch_op.alter_column('complaint_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='The unique id of the complaint',
               existing_nullable=False)

    # ### end Alembic commands ###
