"""order and warning letter approval tables

Revision ID: 970586edecc4
Revises: c2af826d5fc6
Create Date: 2025-05-27 13:13:05.787655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '970586edecc4'
down_revision = 'c2af826d5fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_approvals_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('order_id', sa.Integer(), autoincrement=False, nullable=True, comment='The unique identifier of the order'),
    sa.Column('approved_by_id', sa.Integer(), autoincrement=False, nullable=True, comment='Person who approved the inspection record'),
    sa.Column('order_status', postgresql.ENUM(name='orderstatusenum', create_type=False), autoincrement=False, nullable=True),
    sa.Column('approval_status', sa.Enum('DECISION_PENDING', 'APPROVED', 'NOT_APPROVED', name='orderapprovalstatusenum'), autoincrement=False, nullable=True, comment='State of the order'),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('order_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('approved_by_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('order_status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('approval_status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('order_approvals_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_approvals_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_approvals_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_approvals_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('warning_letter_approvals_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('warning_letter_id', sa.Integer(), autoincrement=False, nullable=True, comment='The unique identifier of the warning letter'),
    sa.Column('approved_by_id', sa.Integer(), autoincrement=False, nullable=True, comment='Person who approved the inspection record'),
    sa.Column('warning_letter_status', postgresql.ENUM(name='warningletterstatusenum', create_type=False), autoincrement=False, nullable=True, comment='Status of the warning letter'),
    sa.Column('approval_status', sa.Enum('DECISION_PENDING', 'APPROVED', 'NOT_APPROVED', name='warningletterapprovalstatusenum'), autoincrement=False, nullable=True, comment='State of the warning letter'),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('warning_letter_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('approved_by_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('warning_letter_status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('approval_status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('warning_letter_approvals_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warning_letter_approvals_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warning_letter_approvals_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_warning_letter_approvals_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('order_approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='The unique identifier of the order'),
    sa.Column('approved_by_id', sa.Integer(), nullable=True, comment='Person who approved the inspection record'),
    sa.Column('order_status', postgresql.ENUM(name='orderstatusenum', create_type=False), nullable=True),
    sa.Column('approval_status', sa.Enum('DECISION_PENDING', 'APPROVED', 'NOT_APPROVED', name='orderapprovalstatusenum'), nullable=True, comment='State of the order'),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['staff_users.id'], name='ir_approval_approved_by_id_staff_user_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_approvals_order_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warning_letter_approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('warning_letter_id', sa.Integer(), nullable=False, comment='The unique identifier of the warning letter'),
    sa.Column('approved_by_id', sa.Integer(), nullable=True, comment='Person who approved the inspection record'),
    sa.Column('warning_letter_status', postgresql.ENUM(name='warningletterstatusenum', create_type=False), nullable=True, comment='Status of the warning letter'),
    sa.Column('approval_status', sa.Enum('DECISION_PENDING', 'APPROVED', 'NOT_APPROVED', name='warningletterapprovalstatusenum'), nullable=True, comment='State of the warning letter'),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['staff_users.id'], name='ir_approval_approved_by_id_staff_user_id_fkey'),
    sa.ForeignKeyConstraint(['warning_letter_id'], ['warning_letters.id'], name='warning_letter_approvals_warning_letter_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_record_approvals', schema=None) as batch_op:
        batch_op.drop_column('approved_date')
        batch_op.drop_column('response_provided')

    with op.batch_alter_table('inspection_record_approvals_version', schema=None) as batch_op:
        batch_op.drop_column('approved_date')
        batch_op.drop_column('approved_date_mod')
        batch_op.drop_column('response_provided')
        batch_op.drop_column('response_provided_mod')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_record_approvals_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_provided_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('response_provided', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Indicate if the proponent has responded or not'))
        batch_op.add_column(sa.Column('approved_date_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('approved_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='The approved date'))

    with op.batch_alter_table('inspection_record_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_provided', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Indicate if the proponent has responded or not'))
        batch_op.add_column(sa.Column('approved_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='The approved date'))

    op.drop_table('warning_letter_approvals')
    op.drop_table('order_approvals')
    with op.batch_alter_table('warning_letter_approvals_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warning_letter_approvals_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_warning_letter_approvals_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_warning_letter_approvals_version_end_transaction_id'))

    op.drop_table('warning_letter_approvals_version')
    with op.batch_alter_table('order_approvals_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_approvals_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_order_approvals_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_order_approvals_version_end_transaction_id'))

    op.drop_table('order_approvals_version')
    op.execute('DROP TYPE orderapprovalstatusenum')
    op.execute('DROP TYPE warningletterapprovalstatusenum')
    # ### end Alembic commands ###
