"""charge recommendatation & restorative justice tables

Revision ID: 9c087d1f34a0
Revises: 8e9ac9d6e233
Create Date: 2025-08-13 17:19:41.972379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c087d1f34a0'
down_revision = '8e9ac9d6e233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_recommendation_inspection_requirement_maps_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('charge_recommendation_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('inspection_requirement_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('charge_recommendation_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inspection_requirement_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('charge_recommendation_inspection_requirement_maps_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_recommendation_inspection_requirement_maps_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_recommendation_inspection_requirement_maps_version_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_recommendation_inspection_requirement_maps_version_end_transaction_id'), ['end_transaction_id'], unique=False)

    op.create_table('charge_recommendations_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('inspection_id', sa.Integer(), autoincrement=False, nullable=True, comment='The unique identifier of the inspection'),
    sa.Column('charge_recommendation_number', sa.String(), autoincrement=False, nullable=True),
    sa.Column('status', sa.Enum('DRAFTING', 'DEPUTY_REVIEW', 'SUBMITTED_TO_CROWN_COUNSEL', 'CEB_NOT_PROCEEDING', name='chargerecommendationstatusenum'), autoincrement=False, nullable=True, comment='Status of the charge recommendation'),
    sa.Column('date_to_crown_counsel', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='Date when the charge recommendation was sent to crown counsel'),
    sa.Column('charge_decision', sa.Enum('APPROVED', 'NOT_PROCEEDING', name='chargedecisionenum'), autoincrement=False, nullable=True, comment='Decision on the charge recommendation'),
    sa.Column('charge_decision_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='Date when the charge decision was made'),
    sa.Column('court_file_number', sa.String(), autoincrement=False, nullable=True, comment='Court file number'),
    sa.Column('court_appearances', sa.Text(), autoincrement=False, nullable=True, comment='Court appearances details'),
    sa.Column('judgment', sa.Enum('GUILTY', 'NOT_GUILTY', name='judgmentenum'), autoincrement=False, nullable=True, comment='Judgment on the charge recommendation'),
    sa.Column('judgment_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='Date when the judgment was made'),
    sa.Column('sentence_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='Date when the sentence was given'),
    sa.Column('sentence_type', sa.String(), autoincrement=False, nullable=True, comment='Type of sentence'),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('inspection_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('charge_recommendation_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_to_crown_counsel_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('charge_decision_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('charge_decision_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('court_file_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('court_appearances_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('judgment_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('judgment_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sentence_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sentence_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('charge_recommendations_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_recommendations_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_recommendations_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_recommendations_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('restorative_justice_inspection_requirement_maps_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('restorative_justice_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('inspection_requirement_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('restorative_justice_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inspection_requirement_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('restorative_justice_inspection_requirement_maps_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restorative_justice_inspection_requirement_maps_version_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restorative_justice_inspection_requirement_maps_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restorative_justice_inspection_requirement_maps_version_operation_type'), ['operation_type'], unique=False)

    op.create_table('restorative_justices_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('inspection_id', sa.Integer(), autoincrement=False, nullable=True, comment='The unique identifier of the inspection'),
    sa.Column('restorative_justice_number', sa.String(), autoincrement=False, nullable=True),
    sa.Column('status', sa.Enum('DRAFTING', 'OPEN', 'CLOSED', name='restorativejusticestatusenum'), autoincrement=False, nullable=True, comment='Status of the restorative justice'),
    sa.Column('restitution_details', sa.Text(), autoincrement=False, nullable=True, comment='Restitution details'),
    sa.Column('date_restitution_complete', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='Date when the restitution was completed'),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('inspection_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('restorative_justice_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('restitution_details_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_restitution_complete_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('restorative_justices_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restorative_justices_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restorative_justices_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_restorative_justices_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('charge_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('inspection_id', sa.Integer(), nullable=False, comment='The unique identifier of the inspection'),
    sa.Column('charge_recommendation_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFTING', 'DEPUTY_REVIEW', 'SUBMITTED_TO_CROWN_COUNSEL', 'CEB_NOT_PROCEEDING', name='chargerecommendationstatusenum'), nullable=True, comment='Status of the charge recommendation'),
    sa.Column('date_to_crown_counsel', sa.DateTime(timezone=True), nullable=True, comment='Date when the charge recommendation was sent to crown counsel'),
    sa.Column('charge_decision', sa.Enum('APPROVED', 'NOT_PROCEEDING', name='chargedecisionenum'), nullable=True, comment='Decision on the charge recommendation'),
    sa.Column('charge_decision_date', sa.DateTime(timezone=True), nullable=True, comment='Date when the charge decision was made'),
    sa.Column('court_file_number', sa.String(), nullable=True, comment='Court file number'),
    sa.Column('court_appearances', sa.Text(), nullable=True, comment='Court appearances details'),
    sa.Column('judgment', sa.Enum('GUILTY', 'NOT_GUILTY', name='judgmentenum'), nullable=True, comment='Judgment on the charge recommendation'),
    sa.Column('judgment_date', sa.DateTime(timezone=True), nullable=True, comment='Date when the judgment was made'),
    sa.Column('sentence_date', sa.DateTime(timezone=True), nullable=True, comment='Date when the sentence was given'),
    sa.Column('sentence_type', sa.String(), nullable=True, comment='Type of sentence'),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name='cr_inspection_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charge_recommendations', schema=None) as batch_op:
        batch_op.create_index('unique_non_deleted_charge_recommendation_number', ['charge_recommendation_number'], unique=True, postgresql_where=False)

    op.create_table('restorative_justices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('inspection_id', sa.Integer(), nullable=False, comment='The unique identifier of the inspection'),
    sa.Column('restorative_justice_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFTING', 'OPEN', 'CLOSED', name='restorativejusticestatusenum'), nullable=True, comment='Status of the restorative justice'),
    sa.Column('restitution_details', sa.Text(), nullable=True, comment='Restitution details'),
    sa.Column('date_restitution_complete', sa.DateTime(timezone=True), nullable=True, comment='Date when the restitution was completed'),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name='rj_inspection_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restorative_justices', schema=None) as batch_op:
        batch_op.create_index('unique_non_deleted_restorative_justice_number', ['restorative_justice_number'], unique=True, postgresql_where=False)

    op.create_table('charge_recommendation_inspection_requirement_maps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('charge_recommendation_id', sa.Integer(), nullable=True),
    sa.Column('inspection_requirement_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['charge_recommendation_id'], ['charge_recommendations.id'], name='charge_recommendation_inspection_map_recommendation_id_fkey'),
    sa.ForeignKeyConstraint(['inspection_requirement_id'], ['inspection_requirements.id'], name='charge_recommendation_inspection_map_requirement_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restorative_justice_inspection_requirement_maps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('restorative_justice_id', sa.Integer(), nullable=True),
    sa.Column('inspection_requirement_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['inspection_requirement_id'], ['inspection_requirements.id'], name='restorative_justice_inspection_map_requirement_id_fkey'),
    sa.ForeignKeyConstraint(['restorative_justice_id'], ['restorative_justices.id'], name='restorative_justice_inspection_map_justice_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restorative_justice_inspection_requirement_maps')
    op.drop_table('charge_recommendation_inspection_requirement_maps')
    with op.batch_alter_table('restorative_justices', schema=None) as batch_op:
        batch_op.drop_index('unique_non_deleted_restorative_justice_number', postgresql_where=False)

    op.drop_table('restorative_justices')
    with op.batch_alter_table('charge_recommendations', schema=None) as batch_op:
        batch_op.drop_index('unique_non_deleted_charge_recommendation_number', postgresql_where=False)

    op.drop_table('charge_recommendations')
    with op.batch_alter_table('restorative_justices_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restorative_justices_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_restorative_justices_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_restorative_justices_version_end_transaction_id'))

    op.drop_table('restorative_justices_version')
    with op.batch_alter_table('restorative_justice_inspection_requirement_maps_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restorative_justice_inspection_requirement_maps_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_restorative_justice_inspection_requirement_maps_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_restorative_justice_inspection_requirement_maps_version_transaction_id'))

    op.drop_table('restorative_justice_inspection_requirement_maps_version')
    with op.batch_alter_table('charge_recommendations_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_recommendations_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_charge_recommendations_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_charge_recommendations_version_end_transaction_id'))

    op.drop_table('charge_recommendations_version')
    with op.batch_alter_table('charge_recommendation_inspection_requirement_maps_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_recommendation_inspection_requirement_maps_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_charge_recommendation_inspection_requirement_maps_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_charge_recommendation_inspection_requirement_maps_version_operation_type'))

    op.drop_table('charge_recommendation_inspection_requirement_maps_version')
    op.execute("DROP TYPE IF EXISTS chargerecommendationstatusenum")
    op.execute("DROP TYPE IF EXISTS chargedecisionenum")
    op.execute("DROP TYPE IF EXISTS judgmentenum")
    op.execute("DROP TYPE IF EXISTS restorativejusticestatusenum")
    # ### end Alembic commands ###
