"""order replacement status

Revision ID: 9ebe29b23084
Revises: 6edfa48316d0
Create Date: 2025-08-25 15:23:04.556827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebe29b23084'
down_revision = '6edfa48316d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    order_replacement_status_enum = sa.Enum('ORIGINAL', 'REPLACED', 'REPLACEMENT', name='orderreplacestatusenum', create_type=True)
    order_replacement_status_enum.create(op.get_bind())
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_replace_status', order_replacement_status_enum, nullable=True))
        batch_op.add_column(sa.Column('replacement_for_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'orders', ['replacement_for_order_id'], ['id'])
    # Set all existing orders to ORIGINAL status
    op.execute("UPDATE orders SET order_replace_status = 'ORIGINAL' WHERE order_replace_status IS NULL")


    with op.batch_alter_table('orders_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_replace_status', order_replacement_status_enum, autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('replacement_for_order_id', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('order_replace_status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('replacement_for_order_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_version', schema=None) as batch_op:
        batch_op.drop_column('replacement_for_order_id_mod')
        batch_op.drop_column('order_replace_status_mod')
        batch_op.drop_column('replacement_for_order_id')
        batch_op.drop_column('order_replace_status')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint("orders_replacement_for_order_id_fkey", type_='foreignkey')
        batch_op.drop_column('replacement_for_order_id')
        batch_op.drop_column('order_replace_status')
    op.execute("DROP TYPE orderreplacestatusenum")

    # ### end Alembic commands ###
