"""new column added for testing

Revision ID: a179cda47b84
Revises: 80afcd35ad35
Create Date: 2025-03-24 11:23:24.929840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a179cda47b84'
down_revision = '80afcd35ad35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_column', sa.Integer(), nullable=True))

    with op.batch_alter_table('topics_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_column', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('new_column_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics_version', schema=None) as batch_op:
        batch_op.drop_column('new_column_mod')
        batch_op.drop_column('new_column')

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('new_column')

    # ### end Alembic commands ###
