"""inspection table changes

Revision ID: a1ef05f78002
Revises: 9671300a284a
Create Date: 2024-09-04 23:49:18.112590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ef05f78002'
down_revision = '9671300a284a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_ir_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('ir_type_id', sa.Integer(), nullable=False, comment='The unique identifier of ir type option'),
    sa.Column('inspection_id', sa.Integer(), nullable=False, comment='The unique identifier of the inspection'),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name='inspection_agencies_inspection_id_fkey'),
    sa.ForeignKeyConstraint(['ir_type_id'], ['ir_type_options.id'], name='inspection_ir_types_type_id_ir_type_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    inspectionstatusenum = sa.Enum('OPEN', 'CLOSED', name='inspectionstatusenum', create_type=True)
    inspectionstatusenum.create(op.get_bind()) 
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspection_status',inspectionstatusenum, nullable=True))
        batch_op.drop_constraint('inspection_ir_type_id_ir_type_options_id_fkey', type_='foreignkey')
        batch_op.drop_column('ir_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ir_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('inspection_ir_type_id_ir_type_options_id_fkey', 'ir_type_options', ['ir_type_id'], ['id'])
        batch_op.drop_column('inspection_status')

    op.drop_table('inspection_ir_types')
    # ### end Alembic commands ###
