"""unique constraint validation changes

Revision ID: a4c0c836847b
Revises: 58ea29190c39
Create Date: 2025-09-10 12:21:59.214121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c0c836847b'
down_revision = '58ea29190c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_resolutions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='The unique identifier of the option',
               existing_comment='The unique identifier of the resolution option',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('complaint_resolutions_id_seq'::regclass)"))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               comment='The name of the option',
               existing_comment='The name of the resolution option',
               existing_nullable=True)

    with op.batch_alter_table('complaint_resolutions_version', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='The unique identifier of the option',
               existing_comment='The unique identifier of the resolution option',
               existing_nullable=False,
               autoincrement=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               comment='The name of the option',
               existing_comment='The name of the resolution option',
               existing_nullable=True,
               autoincrement=False)

    with op.batch_alter_table('complaint_source_contacts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               comment='The title of the complaint source',
               existing_comment='The title of the contact person',
               existing_nullable=True)

    with op.batch_alter_table('complaint_source_contacts_version', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               comment='The title of the complaint source',
               existing_comment='The title of the contact person',
               existing_nullable=True,
               autoincrement=False)
        batch_op.alter_column('title_mod',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='Modification flag for title field')
    # Update unique constraints to include is_deleted = false condition for all auto-generated numbers
    
    # Inspections - ir_number
    op.drop_index('unique_non_deleted_ir_number', table_name='inspections')
    op.create_index('unique_non_deleted_ir_number', 'inspections', ['ir_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    
    # Complaints - complaint_number
    op.drop_index('unique_non_deleted_complaint_file_number', table_name='complaints')
    op.create_index('unique_non_deleted_complaint_file_number', 'complaints', ['complaint_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    
    # Administrative Penalties - administrative_penalty_number
    op.drop_index('unique_non_deleted_administrative_penalty_number', table_name='administrative_penalties')
    op.create_index('unique_non_deleted_administrative_penalty_number', 'administrative_penalties', ['administrative_penalty_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    
    # Warning Letters - warning_letter_number
    op.drop_index('unique_non_deleted_warning_letter_number', table_name='warning_letters')
    op.create_index('unique_non_deleted_warning_letter_number', 'warning_letters', ['warning_letter_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    
    # Orders - order_number
    op.drop_index('unique_non_deleted_order_number', table_name='orders')
    op.create_index('unique_non_deleted_order_number', 'orders', ['order_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    
    # Charge Recommendations - charge_recommendation_number
    op.drop_index('unique_non_deleted_charge_recommendation_number', table_name='charge_recommendations')
    op.create_index('unique_non_deleted_charge_recommendation_number', 'charge_recommendations', ['charge_recommendation_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    
    # Restorative Justice - restorative_justice_number
    op.drop_index('unique_non_deleted_restorative_justice_number', table_name='restorative_justices')
    op.create_index('unique_non_deleted_restorative_justice_number', 'restorative_justices', ['restorative_justice_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    
    # Violation Tickets - vt_number and ticket_number
    op.drop_index('unique_non_deleted_vt_number', table_name='violation_tickets')
    op.create_index('unique_non_deleted_vt_number', 'violation_tickets', ['vt_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    
    op.drop_index('unique_non_deleted_ticket_number', table_name='violation_tickets')
    op.create_index('unique_non_deleted_ticket_number', 'violation_tickets', ['ticket_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    
    # Case Files - case_file_number (create new unique constraint)
    op.drop_index('unique_non_deleted_case_file_number', table_name='case_files')
    op.create_index('unique_non_deleted_case_file_number', 'case_files', ['case_file_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Reverse unique constraint changes - restore original constraints without is_deleted condition
    
    # Case Files - drop new unique constraint
    op.drop_index('unique_non_deleted_case_file_number', table_name='case_files')
    
    # Violation Tickets - restore original constraints
    op.drop_index('unique_non_deleted_ticket_number', table_name='violation_tickets')
    op.create_index('unique_non_deleted_ticket_number', 'violation_tickets', ['ticket_number'], unique=True, postgresql_where=False)
    
    op.drop_index('unique_non_deleted_vt_number', table_name='violation_tickets')
    op.create_index('unique_non_deleted_vt_number', 'violation_tickets', ['vt_number'], unique=True, postgresql_where=False)
    
    # Restorative Justice - restore original constraint
    op.drop_index('unique_non_deleted_restorative_justice_number', table_name='restorative_justices')
    op.create_index('unique_non_deleted_restorative_justice_number', 'restorative_justices', ['restorative_justice_number'], unique=True, postgresql_where=False)
    
    # Charge Recommendations - restore original constraint
    op.drop_index('unique_non_deleted_charge_recommendation_number', table_name='charge_recommendations')
    op.create_index('unique_non_deleted_charge_recommendation_number', 'charge_recommendations', ['charge_recommendation_number'], unique=True, postgresql_where=False)
    
    # Orders - restore original constraint
    op.drop_index('unique_non_deleted_order_number', table_name='orders')
    op.create_index('unique_non_deleted_order_number', 'orders', ['order_number'], unique=True, postgresql_where=False)
    
    # Warning Letters - restore original constraint
    op.drop_index('unique_non_deleted_warning_letter_number', table_name='warning_letters')
    op.create_index('unique_non_deleted_warning_letter_number', 'warning_letters', ['warning_letter_number'], unique=True, postgresql_where=False)
    
    # Administrative Penalties - restore original constraint
    op.drop_index('unique_non_deleted_administrative_penalty_number', table_name='administrative_penalties')
    op.create_index('unique_non_deleted_administrative_penalty_number', 'administrative_penalties', ['administrative_penalty_number'], unique=True, postgresql_where=False)
    
    # Complaints - restore original constraint
    op.drop_index('unique_non_deleted_complaint_file_number', table_name='complaints')
    op.create_index('unique_non_deleted_complaint_file_number', 'complaints', ['complaint_number'], unique=True, postgresql_where=False)
    
    # Inspections - restore original constraint
    op.drop_index('unique_non_deleted_ir_number', table_name='inspections')
    op.create_index('unique_non_deleted_ir_number', 'inspections', ['ir_number'], unique=True, postgresql_where=False)
    
    with op.batch_alter_table('complaint_source_contacts_version', schema=None) as batch_op:
        batch_op.alter_column('title_mod',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='Modification flag for title field')
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               comment='The title of the contact person',
               existing_comment='The title of the complaint source',
               existing_nullable=True,
               autoincrement=False)

    with op.batch_alter_table('complaint_source_contacts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               comment='The title of the contact person',
               existing_comment='The title of the complaint source',
               existing_nullable=True)

    with op.batch_alter_table('complaint_resolutions_version', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               comment='The name of the resolution option',
               existing_comment='The name of the option',
               existing_nullable=True,
               autoincrement=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='The unique identifier of the resolution option',
               existing_comment='The unique identifier of the option',
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('complaint_resolutions', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               comment='The name of the resolution option',
               existing_comment='The name of the option',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='The unique identifier of the resolution option',
               existing_comment='The unique identifier of the option',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('complaint_resolutions_id_seq'::regclass)"))

    # ### end Alembic commands ###
