"""removing inspection requirement index

Revision ID: b888e97fd66e
Revises: 20afe60273fb
Create Date: 2025-01-23 10:48:46.309578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b888e97fd66e'
down_revision = '20afe60273fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_requirements', schema=None) as batch_op:
        batch_op.drop_index('unique_non_deleted_sort_order', postgresql_where='(is_deleted IS FALSE)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_requirements', schema=None) as batch_op:
        batch_op.create_index('unique_non_deleted_sort_order', ['inspection_id', 'sort_order'], unique=True, postgresql_where='(is_deleted IS FALSE)')

    # ### end Alembic commands ###
