"""department details added

Revision ID: bfc8625ce5ce
Revises: 70beb2d53c21
Create Date: 2025-04-01 14:17:21.834174

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'bfc8625ce5ce'
down_revision = '70beb2d53c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_details',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('logo_url', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('phone', sa.String(), nullable=False),
                    sa.Column('website', sa.String(), nullable=True),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.String(
                        length=100), nullable=False),
                    sa.Column('updated_by', sa.String(
                        length=100), nullable=True),
                    sa.Column('is_active', sa.Boolean(),
                              server_default='t', nullable=False),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default='f', nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    # Insert initial department details
    op.execute(
        """
        INSERT INTO department_details (
            logo_url, email, address, phone, website, 
            created_date, created_by, is_active, is_deleted
        ) VALUES (
            'https://nrs.objectstore.gov.bc.ca/prod-epic/logo/eao_log.png',
            'eao.compliance@gov.bc.ca',
            'PO Box 9426 Stn Prov Govt\nVictoria, BC  V8W 9V1',
            '250-387-0131',
            'www.gov.bc.ca/eao',
            NOW(),
            'migration',
            true,
            false
        );
        """
    )

    op.create_table('department_details_version',
                    sa.Column('id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('logo_url', sa.String(),
                              autoincrement=False, nullable=True),
                    sa.Column('email', sa.String(),
                              autoincrement=False, nullable=True),
                    sa.Column('address', sa.String(),
                              autoincrement=False, nullable=True),
                    sa.Column('phone', sa.String(),
                              autoincrement=False, nullable=True),
                    sa.Column('website', sa.String(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_date', sa.DateTime(),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_date', sa.DateTime(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_by', sa.String(length=100),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_by', sa.String(length=100),
                              autoincrement=False, nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default='t',
                              autoincrement=False, nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), server_default='f',
                              autoincrement=False, nullable=True),
                    sa.Column('transaction_id', sa.BigInteger(),
                              autoincrement=False, nullable=False),
                    sa.Column('end_transaction_id',
                              sa.BigInteger(), nullable=True),
                    sa.Column('operation_type',
                              sa.SmallInteger(), nullable=False),
                    sa.Column('logo_url_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('email_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('address_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('phone_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('website_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('created_date_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('updated_date_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('created_by_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('updated_by_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('is_active_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('is_deleted_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'transaction_id')
                    )
    with op.batch_alter_table('department_details_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_details_version_end_transaction_id'), [
                              'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_details_version_operation_type'), [
                              'operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_details_version_transaction_id'), [
                              'transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete the department details data
    op.execute("DELETE FROM department_details;")

    with op.batch_alter_table('department_details_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(
            'ix_department_details_version_transaction_id'))
        batch_op.drop_index(batch_op.f(
            'ix_department_details_version_operation_type'))
        batch_op.drop_index(batch_op.f(
            'ix_department_details_version_end_transaction_id'))

    op.drop_table('department_details_version')
    op.drop_table('department_details')
    # ### end Alembic commands ###
