"""warning letter tables and order changes

Revision ID: c2af826d5fc6
Revises: b531ee6ef2e2
Create Date: 2025-05-09 09:42:18.359781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2af826d5fc6'
down_revision = 'b531ee6ef2e2'
branch_labels = None
depends_on = None


def upgrade():
    # Create temporary enum for order status
    op.execute("CREATE TYPE orderstatusenum_old AS ENUM ('OPEN', 'CLOSED', 'RESCINDED')")
    
    # Update order_status column to use the temporary enum
    op.execute("ALTER TABLE orders ALTER COLUMN order_status TYPE orderstatusenum_old USING order_status::text::orderstatusenum_old")
    op.execute("ALTER TABLE orders_version ALTER COLUMN order_status TYPE orderstatusenum_old USING order_status::text::orderstatusenum_old")
    
    # Drop the original enum
    op.execute('DROP TYPE orderstatusenum')
    
    # Create new enum with CREATED
    op.execute("CREATE TYPE orderstatusenum AS ENUM ('CREATED', 'OPEN', 'CLOSED', 'RESCINDED')")
    
    # Update columns to use new enum
    op.execute("ALTER TABLE orders ALTER COLUMN order_status TYPE orderstatusenum USING order_status::text::orderstatusenum")
    op.execute("ALTER TABLE orders_version ALTER COLUMN order_status TYPE orderstatusenum USING order_status::text::orderstatusenum")
    
    # Drop the temporary enum
    op.execute('DROP TYPE orderstatusenum_old')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warning_letter_inspection_requirement_maps_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('warning_letter_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('inspection_requirement_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('warning_letter_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inspection_requirement_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('warning_letter_inspection_requirement_maps_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warning_letter_inspection_requirement_maps_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warning_letter_inspection_requirement_maps_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_warning_letter_inspection_requirement_maps_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('warning_letters_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('inspection_id', sa.Integer(), autoincrement=False, nullable=True, comment='The unique identifier of the inspection'),
    sa.Column('warning_letter_number', sa.String(), autoincrement=False, nullable=True),
    sa.Column('content', sa.String(), autoincrement=False, nullable=True, comment='Content of the warning letter'),
    sa.Column('date_issued', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='Date when the warning letter was issued'),
    sa.Column('intended_issuance_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='Date when the warning letter was intended to be issued'),
    sa.Column('issuing_officer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'ISSUED', name='warningletterstatusenum'), autoincrement=False, nullable=True, comment='Status of the warning letter'),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('inspection_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('warning_letter_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('content_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_issued_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('intended_issuance_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('issuing_officer_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('warning_letters_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warning_letters_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warning_letters_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_warning_letters_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('warning_letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('inspection_id', sa.Integer(), nullable=False, comment='The unique identifier of the inspection'),
    sa.Column('warning_letter_number', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True, comment='Content of the warning letter'),
    sa.Column('date_issued', sa.DateTime(timezone=True), nullable=True, comment='Date when the warning letter was issued'),
    sa.Column('intended_issuance_date', sa.DateTime(timezone=True), nullable=True, comment='Date when the warning letter was intended to be issued'),
    sa.Column('issuing_officer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ISSUED', name='warningletterstatusenum'), nullable=True, comment='Status of the warning letter'),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name='ir_inspection_id_fkey'),
    sa.ForeignKeyConstraint(['issuing_officer_id'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warning_letters', schema=None) as batch_op:
        batch_op.create_index('unique_non_deleted_warning_letter_number', ['warning_letter_number'], unique=True, postgresql_where=False)

    op.create_table('warning_letter_inspection_requirement_maps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('warning_letter_id', sa.Integer(), nullable=True),
    sa.Column('inspection_requirement_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['inspection_requirement_id'], ['inspection_requirements.id'], name='order_inspection_map_requirement_id_fkey'),
    sa.ForeignKeyConstraint(['warning_letter_id'], ['warning_letters.id'], name='warning_letter_inspection_map_order_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # Create OrderProgressEnum type first
    op.execute("CREATE TYPE orderprogressenum AS ENUM ('DRAFTING', 'DEPUTY_REVIEW', 'APPROVED', 'ISSUED')")

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_progress', sa.Enum('DRAFTING', 'DEPUTY_REVIEW', 'APPROVED', 'ISSUED', name='orderprogressenum'), nullable=True))
        batch_op.create_index('unique_non_deleted_order_number', ['order_number'], unique=True, postgresql_where=False)

    with op.batch_alter_table('orders_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_progress', sa.Enum('DRAFTING', 'DEPUTY_REVIEW', 'APPROVED', 'ISSUED', name='orderprogressenum'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('order_progress_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # Create temporary enum without CREATED
    op.execute("CREATE TYPE orderstatusenum_old AS ENUM ('OPEN', 'CLOSED', 'RESCINDED')")
    
    # Update order_status column to use the temporary enum
    op.execute("ALTER TABLE orders ALTER COLUMN order_status TYPE orderstatusenum_old USING order_status::text::orderstatusenum_old")
    op.execute("ALTER TABLE orders_version ALTER COLUMN order_status TYPE orderstatusenum_old USING order_status::text::orderstatusenum_old")
    
    # Drop the new enum
    op.execute('DROP TYPE orderstatusenum')
    
    # Create original enum without CREATED
    op.execute("CREATE TYPE orderstatusenum AS ENUM ('OPEN', 'CLOSED', 'RESCINDED')")
    
    # Update columns to use original enum
    op.execute("ALTER TABLE orders ALTER COLUMN order_status TYPE orderstatusenum USING order_status::text::orderstatusenum")
    op.execute("ALTER TABLE orders_version ALTER COLUMN order_status TYPE orderstatusenum USING order_status::text::orderstatusenum")
    
    # Drop the temporary enum
    op.execute('DROP TYPE orderstatusenum_old')
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_version', schema=None) as batch_op:
        batch_op.drop_column('order_progress_mod')
        batch_op.drop_column('order_progress')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('unique_non_deleted_order_number', postgresql_where=False)
        batch_op.drop_column('order_progress')

    # Drop the OrderProgressEnum type
    op.execute('DROP TYPE orderprogressenum')

    op.drop_table('warning_letter_inspection_requirement_maps')
    with op.batch_alter_table('warning_letters', schema=None) as batch_op:
        batch_op.drop_index('unique_non_deleted_warning_letter_number', postgresql_where=False)

    op.drop_table('warning_letters')
    with op.batch_alter_table('warning_letters_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warning_letters_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_warning_letters_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_warning_letters_version_end_transaction_id'))

    op.drop_table('warning_letters_version')
    with op.batch_alter_table('warning_letter_inspection_requirement_maps_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warning_letter_inspection_requirement_maps_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_warning_letter_inspection_requirement_maps_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_warning_letter_inspection_requirement_maps_version_end_transaction_id'))

    op.drop_table('warning_letter_inspection_requirement_maps_version')
    op.execute('DROP TYPE warningletterstatusenum')
    # ### end Alembic commands ###
