"""Adjust position titles

Revision ID: c42e6b5815dd
Revises: b888e97fd66e
Create Date: 2025-01-24 09:44:13.649781

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c42e6b5815dd"
down_revision = "b888e97fd66e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projects_version")
    op.execute(
        f"UPDATE positions set name='Deputy Director, Compliance & Enforcement Operations' WHERE name='Deputy Director Operations'"
    )
    op.execute(
        f"UPDATE positions set name='Director, Compliance & Enforcement' WHERE name='Director'"
    )
    op.execute(
        f"INSERT INTO positions(name, description, created_date, created_by) VALUES ('Compliance & Enforcement Specialist','Compliance & Enforcement Specialist',now() at time zone 'utc','system')"
    )
    op.execute(
        f"INSERT INTO positions(name, description, created_date, created_by) VALUES ('Other','Other',now() at time zone 'utc','system')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"UPDATE positions set name='Deputy Director Operations' WHERE name='Deputy Director, Compliance & Enforcement Operations'"
    )
    op.execute(
        f"UPDATE positions set name='Director' WHERE name='Director, Compliance & Enforcement'"
    )
    op.execute(
        f"DELETE FROM positions WHERE name='Compliance & Enforcement Specialist'"
    )
    op.execute(f"DELETE FROM positions WHERE name='Other'")

    op.create_table(
        "projects_version",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_by", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_by", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_deleted",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("transaction_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "end_transaction_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("operation_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "name_mod",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_date_mod",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_date_mod",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_by_mod",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_by_mod",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_active_mod",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_deleted_mod",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", "transaction_id", name="projects_version_pkey"),
    )
    with op.batch_alter_table("projects_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_projects_version_transaction_id", ["transaction_id"], unique=False
        )
        batch_op.create_index(
            "ix_projects_version_operation_type", ["operation_type"], unique=False
        )
        batch_op.create_index(
            "ix_projects_version_end_transaction_id",
            ["end_transaction_id"],
            unique=False,
        )

    # ### end Alembic commands ###
