"""Removing inspection_other_attendance

Revision ID: c4f142cd2183
Revises: ebda0819fd0e
Create Date: 2025-08-27 11:41:53.200507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4f142cd2183'
down_revision = 'ebda0819fd0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection_other_attendances')
    with op.batch_alter_table('inspection_other_attendances_version', schema=None) as batch_op:
        batch_op.drop_index('ix_inspection_other_attendances_version_end_transaction_id')
        batch_op.drop_index('ix_inspection_other_attendances_version_operation_type')
        batch_op.drop_index('ix_inspection_other_attendances_version_transaction_id')

    op.drop_table('inspection_other_attendances_version')
    with op.batch_alter_table('inspection_attendance_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other', sa.String(), nullable=True, comment='Any other attendance for the inspection'))

    with op.batch_alter_table('inspection_attendance_mappings_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other', sa.String(), autoincrement=False, nullable=True, comment='Any other attendance for the inspection'))
        batch_op.add_column(sa.Column('other_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_attendance_mappings_version', schema=None) as batch_op:
        batch_op.drop_column('other_mod')
        batch_op.drop_column('other')

    with op.batch_alter_table('inspection_attendance_mappings', schema=None) as batch_op:
        batch_op.drop_column('other')

    op.create_table('inspection_other_attendances_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('municipal', sa.VARCHAR(), autoincrement=False, nullable=True, comment='The municipal attendance'),
    sa.Column('other', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Any other attendance for the inspection'),
    sa.Column('inspection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('municipal_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('other_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('inspection_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_date_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_date_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_by_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_by_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_active_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_deleted_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name='inspection_other_attendances_version_pkey')
    )
    with op.batch_alter_table('inspection_other_attendances_version', schema=None) as batch_op:
        batch_op.create_index('ix_inspection_other_attendances_version_transaction_id', ['transaction_id'], unique=False)
        batch_op.create_index('ix_inspection_other_attendances_version_operation_type', ['operation_type'], unique=False)
        batch_op.create_index('ix_inspection_other_attendances_version_end_transaction_id', ['end_transaction_id'], unique=False)

    op.create_table('inspection_other_attendances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('municipal', sa.VARCHAR(), autoincrement=False, nullable=True, comment='The municipal attendance'),
    sa.Column('inspection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('other', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Any other attendance for the inspection'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name='other_attendance_inspection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inspection_other_attendances_pkey')
    )
    # ### end Alembic commands ###
