"""restructure complaint req order details and remove requirement details

Revision ID: c8ca64602ac4
Revises: 06fdb92a1550
Create Date: 2025-01-27 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ca64602ac4'
down_revision = '06fdb92a1550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop version tables first
    op.drop_table('complaint_requirement_details_version')
    
    # Drop and recreate complaint_req_order_details_version table with complaint_id instead of req_id
    # Use conditional drop to handle cases where the table might not exist or have wrong schema
    op.execute("DROP TABLE IF EXISTS complaint_req_order_details_version CASCADE")
    op.create_table('complaint_req_order_details_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier of the complaints'),
    sa.Column('complaint_id', sa.Integer(), autoincrement=False, nullable=True, comment='The unique id of the complaint'),
    sa.Column('order_number', sa.String(), autoincrement=False, nullable=True, comment='The order number'),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('complaint_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('order_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    
    # Add new complaint_id column to complaint_req_order_details
    op.add_column('complaint_req_order_details', sa.Column('complaint_id', sa.Integer(), nullable=True))
    
    # Migrate data: copy complaint_id from complaint_requirement_details to complaint_req_order_details
    # Only update records that have valid req_id references
    op.execute("""
        UPDATE complaint_req_order_details 
        SET complaint_id = (
            SELECT complaint_id 
            FROM complaint_requirement_details 
            WHERE complaint_requirement_details.id = complaint_req_order_details.req_id
        )
        WHERE req_id IS NOT NULL
    """)
    
    # Delete any orphaned records that don't have a valid complaint_id
    op.execute("""
        DELETE FROM complaint_req_order_details 
        WHERE complaint_id IS NULL
    """)
    
    # Drop the foreign key constraint from complaint_req_order_details
    op.drop_constraint('details_req_id_complaint_req_detail_id', 'complaint_req_order_details', type_='foreignkey')
    
    # Drop main requirement details table
    op.drop_table('complaint_requirement_details')
    
    # Create foreign key constraint for the new complaint_id column
    op.create_foreign_key('details_complaint_id_complaints_id', 'complaint_req_order_details', 'complaints', ['complaint_id'], ['id'])
    
    # Drop the req_id column
    op.drop_column('complaint_req_order_details', 'req_id')
    
    # Make complaint_id not nullable after data migration
    op.alter_column('complaint_req_order_details', 'complaint_id', nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Recreate complaint_requirement_details table
    op.create_table('complaint_requirement_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name='details_complaint_id_complaints_id'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name='details_topic_id_topics_id'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Recreate version table
    op.create_table('complaint_requirement_details_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('complaint_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    
    # Drop and recreate complaint_req_order_details_version table with req_id
    # Use conditional drop to handle cases where the table might not exist or have wrong schema
    op.execute("DROP TABLE IF EXISTS complaint_req_order_details_version CASCADE")
    op.create_table('complaint_req_order_details_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier of the complaints'),
    sa.Column('req_id', sa.Integer(), autoincrement=False, nullable=True, comment='The unique id of the requirement details'),
    sa.Column('order_number', sa.String(), autoincrement=False, nullable=True, comment='The order number'),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('req_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('order_number_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    
    # Add back req_id column to complaint_req_order_details
    op.add_column('complaint_req_order_details', sa.Column('req_id', sa.Integer(), nullable=True))
    
    # Recreate the old foreign key constraint
    op.create_foreign_key('details_req_id_complaint_req_detail_id', 'complaint_req_order_details', 'complaint_requirement_details', ['req_id'], ['id'])
    
    # Drop the new complaint_id foreign key constraint
    op.drop_constraint('details_complaint_id_complaints_id', 'complaint_req_order_details', type_='foreignkey')
    
    # Drop the complaint_id column
    op.drop_column('complaint_req_order_details', 'complaint_id')
    
    # Handle data migration for req_id - set default values for NULL records
    op.execute("""
        UPDATE complaint_req_order_details 
        SET req_id = 1 
        WHERE req_id IS NULL
    """)
    
    # Make req_id not nullable
    op.alter_column('complaint_req_order_details', 'req_id', nullable=False)
    
    # ### end Alembic commands ### 
