"""adding 'close as note to file' to inspection status

Revision ID: c8cc683f4019
Revises: 026779d28e0c
Create Date: 2025-07-28 12:30:39.964045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cc683f4019'
down_revision = '026779d28e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE inspectionstatusenum ADD VALUE 'CLOSE_AS_NOTE' AFTER 'CANCELED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL doesn't support dropping enum values directly
    # We need to create a new enum type without the value, update all columns, and drop the old type
    
    # Create a temporary enum type without the new value
    op.execute("CREATE TYPE inspectionstatusenum_temp AS ENUM ('OPEN', 'CLOSED', 'CANCELED')")
    
    # Handle all tables that use the enum type
    # First, handle inspections table
    op.execute("ALTER TABLE inspections ALTER COLUMN inspection_status DROP DEFAULT")
    op.execute("ALTER TABLE inspections ADD COLUMN inspection_status_temp inspectionstatusenum_temp")
    op.execute("""
        UPDATE inspections 
        SET inspection_status_temp = 
            CASE 
                WHEN inspection_status::text = 'CLOSE_AS_NOTE' THEN 'CLOSED'::inspectionstatusenum_temp 
                ELSE inspection_status::text::inspectionstatusenum_temp 
            END
    """)
    op.execute("ALTER TABLE inspections DROP COLUMN inspection_status")
    op.execute("ALTER TABLE inspections RENAME COLUMN inspection_status_temp TO inspection_status")
    
    # Handle inspections_version table
    op.execute("ALTER TABLE inspections_version ADD COLUMN inspection_status_temp inspectionstatusenum_temp")
    op.execute("""
        UPDATE inspections_version 
        SET inspection_status_temp = 
            CASE 
                WHEN inspection_status::text = 'CLOSE_AS_NOTE' THEN 'CLOSED'::inspectionstatusenum_temp 
                ELSE inspection_status::text::inspectionstatusenum_temp 
            END
    """)
    op.execute("ALTER TABLE inspections_version DROP COLUMN inspection_status")
    op.execute("ALTER TABLE inspections_version RENAME COLUMN inspection_status_temp TO inspection_status")
    
    # Find and handle any other tables that might depend on the enum
    # This query would identify other tables but we're handling them explicitly
    # for clarity and safety
    
    # Now it's safe to drop the old enum type and rename the new one
    op.execute("DROP TYPE inspectionstatusenum CASCADE")
    op.execute("ALTER TYPE inspectionstatusenum_temp RENAME TO inspectionstatusenum")
    
    # Restore any constraints if needed
    # op.execute("ALTER TABLE inspections ALTER COLUMN inspection_status SET DEFAULT 'OPEN'::inspectionstatusenum")
    # ### end Alembic commands ###
