"""date_created added in CR

Revision ID: cde897a20139
Revises: 4ef153bdbf6d
Create Date: 2024-11-01 10:33:50.908580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde897a20139'
down_revision = '4ef153bdbf6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('continuation_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(timezone=True), nullable=True, comment='The created date of the entry'))

    with op.batch_alter_table('continuation_reports_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(timezone=True), autoincrement=False, nullable=True, comment='The created date of the entry'))
        batch_op.add_column(sa.Column('date_created_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('continuation_reports_version', schema=None) as batch_op:
        batch_op.drop_column('date_created_mod')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('continuation_reports', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
