"""sort order added for positions

Revision ID: d17621c35d33
Revises: 181c7d2318d4
Create Date: 2025-06-12 13:35:38.865354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17621c35d33'
down_revision = '181c7d2318d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('positions_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sort_order_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    positions = [
    {"name": "Compliance & Enforcement Officer", "sort_order": 1},
    {"name": "Senior Compliance & Enforcement Officer", "sort_order": 2},
    {"name": "Deputy Director, Compliance & Enforcement Operations", "sort_order": 3},
    {"name": "Executive Director, Compliance & Enforcement", "sort_order": 4},
    {"name": "Compliance & Enforcement Specialist", "sort_order": 5},
    {"name": "Other", "sort_order": 6},
]
    for position in positions:
        op.execute(f"UPDATE positions SET sort_order={position.get('sort_order')} WHERE name='{position.get('name')}'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions_version', schema=None) as batch_op:
        batch_op.drop_column('sort_order_mod')
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
