"""project table creation

Revision ID: d36894553777
Revises: 774870c99c95
Create Date: 2024-08-21 12:57:47.220758

"""
from alembic import op
import sqlalchemy as sa
import json
import os


# revision identifiers, used by Alembic.
revision = 'd36894553777'
down_revision = '774870c99c95'
branch_labels = None
depends_on = None

def load_json_file(file_name):
    """Load JSON data from a file."""
    file_path = os.path.join(os.path.dirname(__file__), file_name)
    with open(file_path, 'r', encoding='utf-8') as file:
        return json.load(file)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    projects_table = op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ea_certificate', sa.String(length=255), nullable=True),
    sa.Column('proponent_name', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.alter_column('lead_officer_id',
               existing_type=sa.INTEGER(),
               comment='The lead officer who created the case file',
               existing_nullable=True)
        batch_op.create_foreign_key('case_files_project_id_projects_id_fkey', 'projects', ['project_id'], ['id'])
    projects_data = load_json_file("../seed_data/project.json")
    op.bulk_insert(projects_table, projects_data)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.drop_constraint('case_files_project_id_projects_id_fkey', type_='foreignkey')
        batch_op.alter_column('lead_officer_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='The lead officer who created the case file',
               existing_nullable=True)
    op.drop_table('projects')
    # ### end Alembic commands ###
