"""related document image + sentence description

Revision ID: d7a6c2d9d8f3
Revises: 3d9e96992c02
Create Date: 2025-10-20 11:27:16.674828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a6c2d9d8f3'
down_revision = '3d9e96992c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_req_detail_doc_images_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='The unique identifier'),
    sa.Column('req_detail_doc_id', sa.Integer(), autoincrement=False, nullable=True, comment='The requirement detail document id'),
    sa.Column('original_file_name', sa.String(), autoincrement=False, nullable=True, comment='The original filename of the uploaded image'),
    sa.Column('relative_url', sa.String(), autoincrement=False, nullable=True, comment='The actual url of the final uploaded image'),
    sa.Column('is_deleted', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('req_detail_doc_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('original_file_name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('relative_url_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('inspection_req_detail_doc_images_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_req_detail_doc_images_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_req_detail_doc_images_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_req_detail_doc_images_version_req_detail_doc_id'), ['req_detail_doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_req_detail_doc_images_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('inspection_req_detail_doc_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier'),
    sa.Column('req_detail_doc_id', sa.Integer(), nullable=False, comment='The requirement detail document id'),
    sa.Column('original_file_name', sa.String(), nullable=False, comment='The original filename of the uploaded image'),
    sa.Column('relative_url', sa.String(), nullable=False, comment='The actual url of the final uploaded image'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.ForeignKeyConstraint(['req_detail_doc_id'], ['inspection_req_detail_documents.id'], name='inspection_req_detail_doc_images_req_detail_doc_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_req_detail_doc_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_req_detail_doc_images_req_detail_doc_id'), ['req_detail_doc_id'], unique=False)
        batch_op.create_index('unique_non_deleted_req_detail_doc_relative_url', ['req_detail_doc_id', 'relative_url'], unique=True, postgresql_where=False)

    with op.batch_alter_table('charge_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentence_description', sa.String(), nullable=True, comment='Description of the fine'))

    with op.batch_alter_table('charge_recommendations_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentence_description', sa.String(), autoincrement=False, nullable=True, comment='Description of the fine'))
        batch_op.add_column(sa.Column('sentence_description_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge_recommendations_version', schema=None) as batch_op:
        batch_op.drop_column('sentence_description_mod')
        batch_op.drop_column('sentence_description')

    with op.batch_alter_table('charge_recommendations', schema=None) as batch_op:
        batch_op.drop_column('sentence_description')

    with op.batch_alter_table('inspection_req_detail_doc_images', schema=None) as batch_op:
        batch_op.drop_index('unique_non_deleted_req_detail_doc_relative_url', postgresql_where=False)
        batch_op.drop_index(batch_op.f('ix_inspection_req_detail_doc_images_req_detail_doc_id'))

    op.drop_table('inspection_req_detail_doc_images')
    with op.batch_alter_table('inspection_req_detail_doc_images_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_req_detail_doc_images_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_req_detail_doc_images_version_req_detail_doc_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_req_detail_doc_images_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_inspection_req_detail_doc_images_version_end_transaction_id'))

    op.drop_table('inspection_req_detail_doc_images_version')
    # ### end Alembic commands ###
