"""record_prepared_by added in ir

Revision ID: d862826d7c6f
Revises: 0f766f32027e
Create Date: 2025-08-20 12:17:32.681610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd862826d7c6f'
down_revision = '0f766f32027e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_prepared_by_id', sa.Integer(), nullable=True, comment='The unique identifier of the user who prepared the record'))
        batch_op.add_column(sa.Column('record_prepared_by_position_id', sa.Integer(), nullable=True, comment='The unique identifier of the position of the user who prepared the record'))
        batch_op.create_foreign_key('ir_record_prepared_by_id_fkey', 'positions', ['record_prepared_by_position_id'], ['id'])
        batch_op.create_foreign_key('ir_record_prepared_by_position_id_fkey', 'staff_users', ['record_prepared_by_id'], ['id'])

    with op.batch_alter_table('inspection_records_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_prepared_by_id', sa.Integer(), autoincrement=False, nullable=True, comment='The unique identifier of the user who prepared the record'))
        batch_op.add_column(sa.Column('record_prepared_by_position_id', sa.Integer(), autoincrement=False, nullable=True, comment='The unique identifier of the position of the user who prepared the record'))
        batch_op.add_column(sa.Column('record_prepared_by_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('record_prepared_by_position_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # Update existing inspection records with primary officer information
    op.execute("""
        UPDATE inspection_records 
        SET 
            record_prepared_by_id = inspections.primary_officer_id,
            record_prepared_by_position_id = staff_users.position_id
        FROM inspections
        JOIN staff_users ON inspections.primary_officer_id = staff_users.id
        WHERE 
            inspection_records.inspection_id = inspections.id 
            AND inspection_records.record_prepared_by_id IS NULL
            AND inspection_records.is_deleted = false
            AND inspection_records.is_active = true;
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_records_version', schema=None) as batch_op:
        batch_op.drop_column('record_prepared_by_position_id_mod')
        batch_op.drop_column('record_prepared_by_id_mod')
        batch_op.drop_column('record_prepared_by_position_id')
        batch_op.drop_column('record_prepared_by_id')

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.drop_constraint('ir_record_prepared_by_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('ir_record_prepared_by_position_id_fkey', type_='foreignkey')
        batch_op.drop_column('record_prepared_by_position_id')
        batch_op.drop_column('record_prepared_by_id')

    # ### end Alembic commands ###
