"""inspection_status_enum change

Revision ID: e2f642264b01
Revises: 36a31040a452
Create Date: 2024-12-13 09:49:30.968604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2f642264b01'
down_revision = '36a31040a452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE inspectionstatusenum ADD VALUE 'CANCELED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE inspectionstatusenum RENAME TO inspectionstatusenum_old")
    op.execute("CREATE TYPE inspectionstatusenum AS ENUM('OPEN', 'CLOSED')")
    op.execute("""
        ALTER TABLE inspections
        ALTER COLUMN inspection_status
        TYPE inspectionstatusenum
        USING inspection_status::text::inspectionstatusenum
    """)
    # ### end Alembic commands ###
