"""project table

Revision ID: e5c2192f5007
Revises: 774870c99c95
Create Date: 2024-08-20 19:09:41.834422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c2192f5007'
down_revision = '774870c99c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ea_certificate', sa.String(length=255), nullable=True),
    sa.Column('proponent_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.alter_column('lead_officer_id',
               existing_type=sa.INTEGER(),
               comment='The lead officer who created the case file',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.alter_column('lead_officer_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='The lead officer who created the case file',
               existing_nullable=True)

    op.drop_table('projects')
    # ### end Alembic commands ###
