"""inspection record tables

Revision ID: e85b901b6ba6
Revises: 4dd4d28f1914
Create Date: 2025-03-12 10:48:49.044828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85b901b6ba6'
down_revision = '4dd4d28f1914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_record_approvals_version',
                    sa.Column('id', sa.Integer(), autoincrement=False,
                              nullable=False, comment='The unique identifier'),
                    sa.Column('inspection_record_id', sa.Integer(), autoincrement=False,
                              nullable=True, comment='The unique identifier of the inspection record'),
                    sa.Column('date_report_sent', sa.DateTime(timezone=True), autoincrement=False,
                              nullable=True, comment='Date when the report was sent'),
                    sa.Column('date_expected_return', sa.DateTime(timezone=True), autoincrement=False,
                              nullable=True, comment='Expected return date for response'),
                    sa.Column('date_response', sa.DateTime(timezone=True), autoincrement=False,
                              nullable=True, comment='Date when the response was received'),
                    sa.Column('response_provided', sa.Boolean(), autoincrement=False,
                              nullable=True, comment='Indicate if the proponent has responded or not'),
                    sa.Column('approved_by_id', sa.Integer(), autoincrement=False,
                              nullable=True, comment='Person who approved the inspection record'),
                    sa.Column('ir_status_id', sa.Integer(), autoincrement=False,
                              nullable=True, comment='Status of the inspection record'),
                    sa.Column('approval_status', sa.Enum('DECISION_PENDING', 'APPROVED', 'NOT_APPROVED', name='irapprovalstatusenum'),
                              autoincrement=False, nullable=True, comment='State of the inspection record'),
                    sa.Column('created_date', sa.DateTime(),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_date', sa.DateTime(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_by', sa.String(length=100),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_by', sa.String(length=100),
                              autoincrement=False, nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default='t',
                              autoincrement=False, nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), server_default='f',
                              autoincrement=False, nullable=True),
                    sa.Column('transaction_id', sa.BigInteger(),
                              autoincrement=False, nullable=False),
                    sa.Column('end_transaction_id',
                              sa.BigInteger(), nullable=True),
                    sa.Column('operation_type',
                              sa.SmallInteger(), nullable=False),
                    sa.Column('inspection_record_id_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('date_report_sent_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('date_expected_return_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('date_response_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('response_provided_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('approved_by_id_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('ir_status_id_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('approval_status_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('created_date_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('updated_date_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('created_by_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('updated_by_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('is_active_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('is_deleted_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'transaction_id')
                    )
    with op.batch_alter_table('inspection_record_approvals_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_record_approvals_version_end_transaction_id'), [
                              'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_record_approvals_version_operation_type'), [
                              'operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_record_approvals_version_transaction_id'), [
                              'transaction_id'], unique=False)

    op.create_table('inspection_records_version',
                    sa.Column('id', sa.Integer(), autoincrement=False,
                              nullable=False, comment='The unique identifier'),
                    sa.Column('inspection_id', sa.Integer(), autoincrement=False,
                              nullable=True, comment='The unique identifier of the inspection'),
                    sa.Column('ir_status_id', sa.Integer(), autoincrement=False,
                              nullable=True, comment='Status of the inspection record'),
                    sa.Column('mailing_address', sa.String(length=255), autoincrement=False,
                              nullable=True, comment='Mailing address of the associated proponent'),
                    sa.Column('inspection_scope', sa.String(), autoincrement=False,
                              nullable=True, comment='Scope of the inspection'),
                    sa.Column('preliminary_review_details', sa.String(), autoincrement=False,
                              nullable=True, comment='Details of the preliminary review'),
                    sa.Column('finding_statement', sa.String(), autoincrement=False,
                              nullable=True, comment='Finding statement from the inspection'),
                    sa.Column('enforcement_summary', sa.String(), autoincrement=False,
                              nullable=True, comment='Summary of enforcement action'),
                    sa.Column('action_required_by_rp', sa.String(), autoincrement=False,
                              nullable=True, comment='Action required by Regulated Party'),
                    sa.Column('date_issued', sa.DateTime(timezone=True), autoincrement=False,
                              nullable=True, comment='Date when the inspection report was issued'),
                    sa.Column('ir_progress', sa.Enum('PRELIMINARY_DRAFTING', 'PRELIMINARY_DEPUTY_REVIEW', 'PRELIMINARY_APPROVED', 'HOLDER_PRELIMINARY_REVIEW', 'FINALIZING_RECORD',
                                                     'FINAL_DEPUTY_REVIEW', 'FINAL_APPROVED', 'ISSUED', name='irprogressenum'), autoincrement=False, nullable=True, comment='State of the inspection record'),
                    sa.Column('created_date', sa.DateTime(),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_date', sa.DateTime(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_by', sa.String(length=100),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_by', sa.String(length=100),
                              autoincrement=False, nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default='t',
                              autoincrement=False, nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), server_default='f',
                              autoincrement=False, nullable=True),
                    sa.Column('transaction_id', sa.BigInteger(),
                              autoincrement=False, nullable=False),
                    sa.Column('end_transaction_id',
                              sa.BigInteger(), nullable=True),
                    sa.Column('operation_type',
                              sa.SmallInteger(), nullable=False),
                    sa.Column('inspection_id_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('ir_status_id_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('mailing_address_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('inspection_scope_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('preliminary_review_details_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('finding_statement_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('enforcement_summary_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('action_required_by_rp_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('date_issued_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('ir_progress_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('created_date_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('updated_date_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('created_by_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('updated_by_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('is_active_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('is_deleted_mod', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'transaction_id')
                    )
    with op.batch_alter_table('inspection_records_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_records_version_end_transaction_id'), [
                              'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_records_version_operation_type'), [
                              'operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_records_version_transaction_id'), [
                              'transaction_id'], unique=False)

    op.create_table('inspection_records',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False, comment='The unique identifier'),
                    sa.Column('inspection_id', sa.Integer(), nullable=False,
                              comment='The unique identifier of the inspection'),
                    sa.Column('ir_status_id', sa.Integer(), nullable=False,
                              comment='Status of the inspection record'),
                    sa.Column('mailing_address', sa.String(length=255), nullable=True,
                              comment='Mailing address of the associated proponent'),
                    sa.Column('inspection_scope', sa.String(), nullable=True,
                              comment='Scope of the inspection'),
                    sa.Column('preliminary_review_details', sa.String(),
                              nullable=True, comment='Details of the preliminary review'),
                    sa.Column('finding_statement', sa.String(), nullable=True,
                              comment='Finding statement from the inspection'),
                    sa.Column('enforcement_summary', sa.String(), nullable=True,
                              comment='Summary of enforcement action'),
                    sa.Column('action_required_by_rp', sa.String(), nullable=True,
                              comment='Action required by Regulated Party'),
                    sa.Column('date_issued', sa.DateTime(timezone=True), nullable=True,
                              comment='Date when the inspection report was issued'),
                    sa.Column('ir_progress', sa.Enum('PRELIMINARY_DRAFTING', 'PRELIMINARY_DEPUTY_REVIEW', 'PRELIMINARY_APPROVED', 'HOLDER_PRELIMINARY_REVIEW',
                                                     'FINALIZING_RECORD', 'FINAL_DEPUTY_REVIEW', 'FINAL_APPROVED', 'ISSUED', name='irprogressenum'), nullable=True, comment='State of the inspection record'),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.String(
                        length=100), nullable=False),
                    sa.Column('updated_by', sa.String(
                        length=100), nullable=True),
                    sa.Column('is_active', sa.Boolean(),
                              server_default='t', nullable=False),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default='f', nullable=False),
                    sa.ForeignKeyConstraint(
                        ['inspection_id'], ['inspections.id'], name='ir_inspection_id_fkey'),
                    sa.ForeignKeyConstraint(['ir_status_id'], [
                        'ir_status_options.id'], name='ir_status_id_status_options_fkey'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('inspection_record_approvals',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False, comment='The unique identifier'),
                    sa.Column('inspection_record_id', sa.Integer(
                    ), nullable=False, comment='The unique identifier of the inspection record'),
                    sa.Column('date_report_sent', sa.DateTime(timezone=True),
                              nullable=True, comment='Date when the report was sent'),
                    sa.Column('date_expected_return', sa.DateTime(timezone=True),
                              nullable=True, comment='Expected return date for response'),
                    sa.Column('date_response', sa.DateTime(timezone=True),
                              nullable=True, comment='Date when the response was received'),
                    sa.Column('response_provided', sa.Boolean(), nullable=True,
                              comment='Indicate if the proponent has responded or not'),
                    sa.Column('approved_by_id', sa.Integer(), nullable=True,
                              comment='Person who approved the inspection record'),
                    sa.Column('ir_status_id', sa.Integer(), nullable=False,
                              comment='Status of the inspection record'),
                    sa.Column('approval_status', sa.Enum('DECISION_PENDING', 'APPROVED', 'NOT_APPROVED',
                                                         name='irapprovalstatusenum'), nullable=True, comment='State of the inspection record'),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.String(
                        length=100), nullable=False),
                    sa.Column('updated_by', sa.String(
                        length=100), nullable=True),
                    sa.Column('is_active', sa.Boolean(),
                              server_default='t', nullable=False),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default='f', nullable=False),
                    sa.ForeignKeyConstraint(['approved_by_id'], [
                        'staff_users.id'], name='ir_approval_approved_by_id_staff_user_id_fkey'),
                    sa.ForeignKeyConstraint(['inspection_record_id'], [
                        'inspection_records.id'], name='ir_approvals_ir_id_fkey'),
                    sa.ForeignKeyConstraint(['ir_status_id'], [
                        'ir_status_options.id'], name='ir_status_id_status_options_fkey'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection_record_approvals')
    op.drop_table('inspection_records')
    with op.batch_alter_table('inspection_records_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(
            'ix_inspection_records_version_transaction_id'))
        batch_op.drop_index(batch_op.f(
            'ix_inspection_records_version_operation_type'))
        batch_op.drop_index(batch_op.f(
            'ix_inspection_records_version_end_transaction_id'))

    op.drop_table('inspection_records_version')
    with op.batch_alter_table('inspection_record_approvals_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(
            'ix_inspection_record_approvals_version_transaction_id'))
        batch_op.drop_index(batch_op.f(
            'ix_inspection_record_approvals_version_operation_type'))
        batch_op.drop_index(batch_op.f(
            'ix_inspection_record_approvals_version_end_transaction_id'))

    op.drop_table('inspection_record_approvals_version')
    op.execute("DROP TYPE irprogressenum")
    op.execute("DROP TYPE irapprovalstatusenum")
    # ### end Alembic commands ###
