"""Appendix table creation

Revision ID: e8a29d9b9a0d
Revises: 231cb1f8b9e7
Create Date: 2025-02-22 23:34:10.952601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a29d9b9a0d'
down_revision = '231cb1f8b9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appendices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appendix_no', sa.Integer(), nullable=False),
    sa.Column('document_title', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appendix_no')
    )
    op.create_table('appendices_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('appendix_no', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('document_title', sa.String(), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('appendix_no_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('document_title_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_date_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('appendices_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appendices_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appendices_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_appendices_version_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appendices_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appendices_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_appendices_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_appendices_version_end_transaction_id'))

    op.drop_table('appendices_version')
    op.drop_table('appendices')
    # ### end Alembic commands ###
