"""inspection_attendance option reorder

Revision ID: ebda0819fd0e
Revises: d862826d7c6f
Create Date: 2025-08-27 10:09:26.588119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebda0819fd0e'
down_revision = 'd862826d7c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove Municipal option (id=3) and update any references to Other (id=7)
    op.execute("UPDATE inspection_attendance_mappings SET attendance_option_id = 7 WHERE attendance_option_id = 3")
    op.execute("DELETE FROM inspection_attendance_options WHERE id = 3")
    
    # Reorder the options with new sort_order values
    # 1. Certificate Holder / Regulated Party Representative (id=5)
    op.execute("UPDATE inspection_attendance_options SET sort_order = 1 WHERE id = 5")
    
    # 2. Independent Environmental Monitor (id=4) 
    op.execute("UPDATE inspection_attendance_options SET sort_order = 2 WHERE id = 4")
    
    # 3. Agencies (id=1)
    op.execute("UPDATE inspection_attendance_options SET sort_order = 3 WHERE id = 1")
    
    # 4. First Nations (id=2)
    op.execute("UPDATE inspection_attendance_options SET sort_order = 4 WHERE id = 2")
    
    # 5. Other (id=7)
    op.execute("UPDATE inspection_attendance_options SET sort_order = 5 WHERE id = 7")
    
    # 6. Attending Officers (id=8) - keep at end
    op.execute("UPDATE inspection_attendance_options SET sort_order = 6 WHERE id = 8")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Restore original sort_order values
    op.execute("UPDATE inspection_attendance_options SET sort_order = 1 WHERE id = 1")  # Agencies
    op.execute("UPDATE inspection_attendance_options SET sort_order = 2 WHERE id = 2")  # First Nations
    op.execute("UPDATE inspection_attendance_options SET sort_order = 4 WHERE id = 4")  # Independent Environmental Monitor
    op.execute("UPDATE inspection_attendance_options SET sort_order = 5 WHERE id = 5")  # Certificate Holder
    op.execute("UPDATE inspection_attendance_options SET sort_order = 7 WHERE id = 7")  # Other
    op.execute("UPDATE inspection_attendance_options SET sort_order = 7 WHERE id = 8")  # Attending Officers
    
    # Restore Municipal option
    op.execute("INSERT INTO inspection_attendance_options (id, name, sort_order, created_date, created_by) VALUES (3, 'Municipal', 3, now() at time zone 'utc', 'system')")
    
    # ### end Alembic commands ###
