"""inspection_attendance_option_changes

Revision ID: ef5bf004ac09
Revises: 764aa8ef55f8
Create Date: 2025-04-29 10:25:23.470088

"""
from alembic import op
import sqlalchemy as sa
from compliance_api.models.inspection.inspection_enum import InspectionAttendanceOptionEnum


# revision identifiers, used by Alembic.
revision = 'ef5bf004ac09'
down_revision = '764aa8ef55f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Update the attendance id 5 with Certificate Holder / Regulated Party Representative
    op.execute("UPDATE inspection_attendance_options SET name = 'Certificate Holder / Regulated Party Representative' WHERE id = 5")
    # Update the inspection_attendance_attendance_mapping with all the attendance option id 6 to 5
    op.execute("UPDATE inspection_attendance_mappings SET attendance_option_id = 5 WHERE attendance_option_id = 6")
    # Delete the attendance option with id 6 which is Regulated Party Representative
    op.execute("DELETE FROM inspection_attendance_options WHERE id = 6")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Insert the options with their specific IDs
    op.execute(
        "INSERT INTO inspection_attendance_options (id, name) VALUES (5, 'Certificate Holder Representative')"
    )
    op.execute(
        "INSERT INTO inspection_attendance_options (id, name) VALUES (6, 'Regulated Party Representative')"
    )
    # ### end Alembic commands ###
