"""add output_format to document_jobs

Revision ID: f9ce82110047
Revises: b3f1c9a47d28
Create Date: 2026-07-06 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ce82110047'
down_revision = 'b3f1c9a47d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_format', sa.String(), server_default='pdf', nullable=False, comment='The output format of the document job (pdf or docx)'))

    with op.batch_alter_table('document_jobs_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_format', sa.String(), autoincrement=False, nullable=True, comment='The output format of the document job (pdf or docx)'))
        batch_op.add_column(sa.Column('output_format_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_jobs_version', schema=None) as batch_op:
        batch_op.drop_column('output_format_mod')
        batch_op.drop_column('output_format')

    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.drop_column('output_format')

    # ### end Alembic commands ###
