"""adding index to complaint and inspection

Revision ID: ff7d002a8a12
Revises: 3aa492aa47db
Create Date: 2025-02-12 10:19:22.289152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7d002a8a12'
down_revision = '3aa492aa47db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index('ix_complaints_complaint_number')
        batch_op.create_index(batch_op.f('ix_complaints_complaint_number'), ['complaint_number'], unique=False)
        batch_op.create_index('unique_non_deleted_complaint_file_number', ['complaint_number'], unique=True, postgresql_where=False)

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index('ix_inspections_ir_number')
        batch_op.create_index(batch_op.f('ix_inspections_ir_number'), ['ir_number'], unique=False)
        batch_op.create_index('unique_non_deleted_ir_number', ['ir_number'], unique=True, postgresql_where=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index('unique_non_deleted_ir_number', postgresql_where=False)
        batch_op.drop_index(batch_op.f('ix_inspections_ir_number'))
        batch_op.create_index('ix_inspections_ir_number', ['ir_number'], unique=True)

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index('unique_non_deleted_complaint_file_number', postgresql_where=False)
        batch_op.drop_index(batch_op.f('ix_complaints_complaint_number'))
        batch_op.create_index('ix_complaints_complaint_number', ['complaint_number'], unique=True)

    # ### end Alembic commands ###
