name: Compliance WEB CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - "compliance-web/**"
  push:
    branches:
      - develop

defaults:
  run:
    shell: bash
    working-directory: ./compliance-web

jobs:
  setup-job:
    runs-on: ubuntu-20.04

    if: github.repository == 'bcgov/EPIC.compliance'

    steps:
      - uses: actions/checkout@v2
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      - name: Lint
        id: lint
        run: |
          npm run lint

  testing:
    needs: setup-job
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Test with Cypress
        id: test
        run: |
          npx cypress run --component --headed --browser chrome

      - name: Generate Coverage Report
        run: |
          npx nyc report --reporter=text-summary  > coverage-summary.txt
  
      - name: Post Coverage Summary to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const coverageSummary = fs.readFileSync('coverage-summary.txt', 'utf8');
            const { context, github } = require('@actions/github');

            const prComment = `### Code Coverage Summary\n\`\`\`plaintext\n${coverageSummary}\n\`\`\``;
            const comment = await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: prComment,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-check:
    needs: setup-job
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      - name: build to check strictness
        id: build
        run: |
          npm run build --quiet || true
