name: Compliance WEB CI

on:
  pull_request:
    branches:
      - develop
      - 'release/*'
    paths:
      - "compliance-web/**"
  push:
    branches:
      - develop

defaults:
  run:
    shell: bash
    working-directory: ./compliance-web

jobs:
  setup-job:
    runs-on: ubuntu-latest

    if: github.repository == 'bcgov/EPIC.compliance'

    steps:
      - uses: actions/checkout@v6
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Lint
        id: lint
        run: |
          npm run lint

  testing:
    needs: setup-job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb
        working-directory: .

      - name: Test with Cypress
        id: test
        run: |
          xvfb-run --auto-servernum npx cypress run --component --headed --browser chrome

  build-check:
    needs: setup-job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Install dependencies
        run: |
          npm install
      - name: build to check strictness
        id: build
        run: |
          npm run build --quiet || true
